/**
 * SessionRegistry - Manages spawnIntentId to sessionId bindings
 *
 * Implements the first-contact binding strategy where:
 * 1. Daemon pre-generates spawnIntentId and registers pending record
 * 2. Thin Plugin/Adapter binds real sessionId on first event arrival
 * 3. Subsequent lookups can find session by either ID
 *
 * Requirements: 4.2
 */

/**
 * Session binding state
 */
export type BindingState = 'pending' | 'bound' | 'released';

/**
 * Session binding record
 */
export interface SessionBinding {
  /** The spawn intent ID (pre-generated by Daemon) */
  spawnIntentId: string;
  /** The actual session ID (from OpenCode) */
  sessionId: string;
  /** Current binding state */
  state: BindingState;
  /** When the binding was created */
  createdAt: Date;
  /** When the binding was last updated */
  updatedAt: Date;
  /** Agent role for this session */
  agentRole: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Session binding request
 */
export interface SessionBindingRequest {
  /** Pre-generated spawn intent ID */
  spawnIntentId: string;
  /** Agent role */
  agentRole: string;
  /** Optional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Session binding result
 */
export interface SessionBindingResult {
  /** Whether the operation succeeded */
  success: boolean;
  /** The session ID */
  sessionId?: string;
  /** The spawn intent ID */
  spawnIntentId?: string;
  /** Error message if failed */
  error?: string;
}

/**
 * Query options for finding sessions
 */
export interface SessionQuery {
  /** Find by spawn intent ID */
  spawnIntentId?: string;
  /** Find by session ID */
  sessionId?: string;
  /** Filter by state */
  state?: BindingState;
}

/**
 * SessionRegistryError - Custom error class
 */
export class SessionRegistryError extends Error {
  constructor(
    message: string,
    public readonly code: 'NOT_FOUND' | 'ALREADY_BOUND' | 'INVALID_STATE' | 'BINDING_FAILED',
    public readonly details?: unknown
  ) {
    super(message);
    this.name = 'SessionRegistryError';
  }
}

/**
 * SessionRegistry - Manages session bindings
 *
 * Provides:
 * - Registration of pending spawn intents
 * - First-contact binding (bind on first event)
 * - Bidirectional lookup (by spawnIntentId or sessionId)
 * - Session state tracking
 *
 * Requirements: 4.2
 */
export class SessionRegistry {
  // Primary index: spawnIntentId -> SessionBinding
  private bySpawnIntentId: Map<string, SessionBinding> = new Map();
  
  // Secondary index: sessionId -> SessionBinding
  private bySessionId: Map<string, SessionBinding> = new Map();

  // Configuration
  private readonly bindingTimeout: number;
  private readonly maxBindings: number;

  /**
   * Create a new SessionRegistry
   * @param config - Optional configuration
   */
  constructor(config?: { bindingTimeout?: number; maxBindings?: number }) {
    this.bindingTimeout = config?.bindingTimeout ?? 60000; // 1 minute default
    this.maxBindings = config?.maxBindings ?? 10000; // 10000 max bindings
  }

  /**
   * Register a pending spawn intent (pre-binding)
   *
   * Called by Daemon before OpenCode session starts.
   * Creates a pending record that will be bound on first contact.
   *
   * @param request - Binding request with spawnIntentId
   * @returns SessionBindingResult
   */
  registerPending(request: SessionBindingRequest): SessionBindingResult {
    // Check capacity
    if (this.bySpawnIntentId.size >= this.maxBindings) {
      return {
        success: false,
        error: `Maximum bindings (${this.maxBindings}) reached`,
      };
    }

    // Check if already registered
    if (this.bySpawnIntentId.has(request.spawnIntentId)) {
      const existing = this.bySpawnIntentId.get(request.spawnIntentId)!;
      
      // If already bound, return the bound session
      if (existing.state === 'bound') {
        return {
          success: true,
          sessionId: existing.sessionId,
          spawnIntentId: request.spawnIntentId,
        };
      }
      
      // If pending, return existing
      return {
        success: true,
        sessionId: undefined,
        spawnIntentId: request.spawnIntentId,
      };
    }

    const now = new Date();
    const binding: SessionBinding = {
      spawnIntentId: request.spawnIntentId,
      sessionId: '', // Will be set on binding
      state: 'pending',
      createdAt: now,
      updatedAt: now,
      agentRole: request.agentRole,
      metadata: request.metadata,
    };

    // Store in primary index
    this.bySpawnIntentId.set(request.spawnIntentId, binding);

    return {
      success: true,
      spawnIntentId: request.spawnIntentId,
    };
  }

  /**
   * Bind spawn intent to session ID (first-contact binding)
   *
   * Called when first event arrives from OpenCode.
   * This is the core of the first-contact binding strategy.
   *
   * @param spawnIntentId - The pre-registered spawn intent ID
   * @param sessionId - The actual session ID from OpenCode
   * @returns SessionBindingResult
   */
  bind(spawnIntentId: string, sessionId: string): SessionBindingResult {
    // Check if spawn intent exists
    const binding = this.bySpawnIntentId.get(spawnIntentId);
    
    if (!binding) {
      // Auto-register if not found (for backward compatibility)
      const now = new Date();
      const newBinding: SessionBinding = {
        spawnIntentId,
        sessionId,
        state: 'bound',
        createdAt: now,
        updatedAt: now,
        agentRole: 'unknown',
      };
      
      this.bySpawnIntentId.set(spawnIntentId, newBinding);
      this.bySessionId.set(sessionId, newBinding);
      
      return {
        success: true,
        spawnIntentId,
        sessionId,
      };
    }

    // Check if already bound to different session
    if (binding.state === 'bound' && binding.sessionId !== sessionId) {
      return {
        success: false,
        error: `Spawn intent ${spawnIntentId} already bound to session ${binding.sessionId}`,
      };
    }

    // Update binding
    const now = new Date();
    binding.sessionId = sessionId;
    binding.state = 'bound';
    binding.updatedAt = now;

    // Add to secondary index
    this.bySessionId.set(sessionId, binding);

    return {
      success: true,
      spawnIntentId,
      sessionId,
    };
  }

  /**
   * Release a binding
   *
   * @param sessionId - Session ID to release
   * @returns Whether release succeeded
   */
  release(sessionId: string): boolean {
    const binding = this.bySessionId.get(sessionId);
    
    if (!binding) {
      return false;
    }

    // Update state
    binding.state = 'released';
    binding.updatedAt = new Date();

    // Remove from indices (keep for audit trail in production)
    this.bySpawnIntentId.delete(binding.spawnIntentId);
    this.bySessionId.delete(sessionId);

    return true;
  }

  /**
   * Find binding by spawn intent ID
   *
   * @param spawnIntentId - Spawn intent ID to find
   * @returns SessionBinding or undefined
   */
  findBySpawnIntentId(spawnIntentId: string): SessionBinding | undefined {
    return this.bySpawnIntentId.get(spawnIntentId);
  }

  /**
   * Find binding by session ID
   *
   * @param sessionId - Session ID to find
   * @returns SessionBinding or undefined
   */
  findBySessionId(sessionId: string): SessionBinding | undefined {
    return this.bySessionId.get(sessionId);
  }

  /**
   * Find binding by either ID (convenience method)
   *
   * @param query - Query with either spawnIntentId or sessionId
   * @returns SessionBinding or undefined
   */
  find(query: SessionQuery): SessionBinding | undefined {
    if (query.spawnIntentId) {
      return this.findBySpawnIntentId(query.spawnIntentId);
    }
    if (query.sessionId) {
      return this.findBySessionId(query.sessionId);
    }
    return undefined;
  }

  /**
   * Get all bindings matching a query
   *
   * @param query - Query filter
   * @returns Array of matching bindings
   */
  findAll(query: SessionQuery): SessionBinding[] {
    const results: SessionBinding[] = [];
    
    for (const binding of this.bySpawnIntentId.values()) {
      let matches = true;
      
      if (query.state && binding.state !== query.state) {
        matches = false;
      }
      
      if (query.spawnIntentId && binding.spawnIntentId !== query.spawnIntentId) {
        matches = false;
      }
      
      if (query.sessionId && binding.sessionId !== query.sessionId) {
        matches = false;
      }
      
      if (matches) {
        results.push(binding);
      }
    }
    
    return results;
  }

  /**
   * Get pending bindings count
   */
  getPendingCount(): number {
    return this.findAll({ state: 'pending' }).length;
  }

  /**
   * Get bound sessions count
   */
  getBoundCount(): number {
    return this.findAll({ state: 'bound' }).length;
  }

  /**
   * Get total bindings count
   */
  getTotalCount(): number {
    return this.bySpawnIntentId.size;
  }

  /**
   * Check if a spawn intent is bound
   *
   * @param spawnIntentId - Spawn intent ID to check
   * @returns Whether the spawn intent is bound
   */
  isBound(spawnIntentId: string): boolean {
    const binding = this.bySpawnIntentId.get(spawnIntentId);
    return binding?.state === 'bound';
  }

  /**
   * Check if a session exists
   *
   * @param sessionId - Session ID to check
   * @returns Whether the session exists
   */
  hasSession(sessionId: string): boolean {
    return this.bySessionId.has(sessionId);
  }

  /**
   * Clean up expired pending bindings
   *
   * @returns Number of bindings cleaned up
   */
  cleanupExpired(): number {
    const now = Date.now();
    let cleaned = 0;
    
    for (const [spawnIntentId, binding] of this.bySpawnIntentId.entries()) {
      if (binding.state === 'pending') {
        const age = now - binding.createdAt.getTime();
        if (age > this.bindingTimeout) {
          this.bySpawnIntentId.delete(spawnIntentId);
          if (binding.sessionId) {
            this.bySessionId.delete(binding.sessionId);
          }
          cleaned++;
        }
      }
    }
    
    return cleaned;
  }

  /**
   * Clear all bindings (for testing)
   */
  clear(): void {
    this.bySpawnIntentId.clear();
    this.bySessionId.clear();
  }

  /**
   * Get registry statistics
   */
  getStats(): {
    total: number;
    pending: number;
    bound: number;
    released: number;
  } {
    let pending = 0;
    let bound = 0;
    let released = 0;
    
    for (const binding of this.bySpawnIntentId.values()) {
      switch (binding.state) {
        case 'pending':
          pending++;
          break;
        case 'bound':
          bound++;
          break;
        case 'released':
          released++;
          break;
      }
    }
    
    return {
      total: this.bySpawnIntentId.size,
      pending,
      bound,
      released,
    };
  }
}