import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const repoRoot = resolve(import.meta.dirname, '../../../..');
const experiencePath = join(
  repoRoot,
  'docs/rule/specforge-development-error-ledger-and-experience.md',
);
const currentHandoffPath = join(
  repoRoot,
  'docs/implementation/architecture-consistency/current-handoff.md',
);
const psvImplementationPath = join(
  repoRoot,
  'docs/implementation/architecture-consistency/P0-project-spec-version-binding-defect.md',
);
const p0ContractClosurePath = join(
  repoRoot,
  'docs/implementation/architecture-consistency/P0-contract-consumer-closure.md',
);
const rootAgentsPath = join(repoRoot, 'AGENTS.md');
const userLevelAgentsPath = join(repoRoot, 'setup/userlevel-opencode/AGENTS.md');
const unicodeClipboardCmdPath = join(repoRoot, 'scripts/windows/copy-utf8-to-clipboard.cmd');
const unicodeClipboardPythonPath = join(repoRoot, 'scripts/windows/copy-utf8-to-clipboard.py');

function readSection(document: string, heading: string, nextHeading: string): string {
  const start = document.indexOf(heading);
  const end = document.indexOf(nextHeading);
  if (start < 0 || end <= start) return '';
  return document.slice(start, end);
}

describe('SpecForge development experience pre-read gate', () => {
  it('contains substantive experience rules and mandatory checks', () => {
    const document = readFileSync(experiencePath, 'utf-8');
    const experience = readSection(
      document,
      '# 第三部分：工程经验总则',
      '# 第四部分：修改前强制检查',
    );
    const checklist = readSection(
      document,
      '# 第四部分：修改前强制检查',
      '# 第五部分：错误台账维护规则',
    );

    const experienceRuleIds = experience.match(/^## EXP-\d{3}：/gm) ?? [];
    expect(experience.trim().length).toBeGreaterThan(500);
    expect(experienceRuleIds.length).toBeGreaterThanOrEqual(50);
    expect(experienceRuleIds).toContain('## EXP-021：');
    expect(experienceRuleIds).toContain('## EXP-022：');
    expect(experienceRuleIds).toContain('## EXP-023：');
    expect(experienceRuleIds).toContain('## EXP-024：');
    expect(experienceRuleIds).toContain('## EXP-025：');
    expect(experienceRuleIds).toContain('## EXP-026：');
    expect(experienceRuleIds).toContain('## EXP-027：');
    expect(experienceRuleIds).toContain('## EXP-028：');
    expect(experienceRuleIds).toContain('## EXP-029：');
    expect(experienceRuleIds).toContain('## EXP-030：');
    expect(experienceRuleIds).toContain('## EXP-031：');
    expect(experienceRuleIds).toContain('## EXP-032：');
    expect(experienceRuleIds).toContain('## EXP-033：');
    expect(experienceRuleIds).toContain('## EXP-034：');
    expect(experienceRuleIds).toContain('## EXP-035：');
    expect(experienceRuleIds).toContain('## EXP-036：');
    expect(experienceRuleIds).toContain('## EXP-037：');
    expect(experienceRuleIds).toContain('## EXP-038：');
    expect(experienceRuleIds).toContain('## EXP-039：');
    expect(experienceRuleIds).toContain('## EXP-040：');
    expect(experienceRuleIds).toContain('## EXP-041：');
    expect(experienceRuleIds).toContain('## EXP-042：');
    expect(experienceRuleIds).toContain('## EXP-043：');
    expect(experienceRuleIds).toContain('## EXP-044：');
    expect(experienceRuleIds).toContain('## EXP-045：');
    expect(experienceRuleIds).toContain('## EXP-046：');
    expect(experienceRuleIds).toContain('## EXP-047：');
    expect(experienceRuleIds).toContain('## EXP-048：');
    expect(experienceRuleIds).toContain('## EXP-049：');
    expect(experienceRuleIds).toContain('## EXP-050：');
    expect(experienceRuleIds).toContain('## EXP-051：');
    expect(experienceRuleIds).toContain('## EXP-052：');
    expect(experienceRuleIds).toContain('## EXP-053：');
    expect(experienceRuleIds).toContain('## EXP-054：');
    expect(experienceRuleIds).toContain('## EXP-055：');
    expect(experienceRuleIds).toContain('## EXP-056：');
    expect(experienceRuleIds).toContain('## EXP-057：');
    expect(experienceRuleIds).toContain('## EXP-058：');
    expect(experienceRuleIds).toContain('## EXP-059：');
    expect(experienceRuleIds).toContain('## EXP-060：');
    expect(experienceRuleIds).toContain('## EXP-061：');
    expect(experienceRuleIds).toContain('## EXP-062：');
    expect(experienceRuleIds).toContain('## EXP-063：');
    expect(experienceRuleIds).toContain('## EXP-064：');
    expect(experienceRuleIds).toContain('## EXP-065：');

    expect(experienceRuleIds).toContain('## EXP-088：');
    expect(experienceRuleIds).toContain('## EXP-089：');
    expect(experienceRuleIds).toContain('## EXP-090：');
    expect(experienceRuleIds).toContain('## EXP-091：');
    expect(experienceRuleIds).toContain('## EXP-092：');

    expect(checklist.trim().length).toBeGreaterThan(500);
    expect(checklist).toContain('APPLICABLE_EXPERIENCE_RULES');
    expect(checklist).toContain('NONE_FOUND');
    expect(checklist).toContain('fail closed');
    expect(checklist).toContain('多产物交付已先冻结主文件');
    expect(checklist).toContain('迁移脚本已分离 SOURCE_CONTRACT 与 TARGET_CONTRACT');
    expect(checklist).toContain('已执行重复错误检查');
    expect(checklist).toContain('生产错误信息、注释、帮助文本和示例已与当前唯一权威路径一致');
    expect(checklist).toContain('新生产写入和新测试夹具未使用 legacy/compatibility 只读路径');
    expect(checklist).toContain('包外 CMD 已覆盖下载文件检查、解压、入口定位和启动标记');
    expect(checklist).toContain('下载 ZIP 不存在、解压失败或 RUN.cmd 未启动时也会输出最小 FEEDBACK TO CHATGPT');
    expect(checklist).toContain('Candidate Gate → User Decision → Merge → Verification/Formal Version → Close');
    expect(checklist).toContain('正式 handler 或 runRequiredGates 执行');
    expect(checklist).toContain('Gate check_id、错误码、Schema 字段和状态枚举变更已同步全部过滤、聚合、豁免、报告和测试消费者');
    expect(checklist).toContain('业务规则已落在全部生产入口共同调用的责任层');
    expect(checklist).toContain('最终证据包已包含全部变化文件正文');
    expect(checklist).toContain('完整 tracked diff、全部 untracked 文件正文');
    expect(checklist).toContain('最终状态文档已根据同一份验证证据对账');
    expect(checklist).toContain('迁移/升级工具已先识别 SOURCE/TARGET 状态');
    expect(checklist).toContain('状态对账目标描述成功结束后的下一阶段');
    expect(checklist).toContain('强制经验门禁已同步仓库根 AGENTS.md');
    expect(checklist).toContain('提交依赖状态已在实现提交和推送成功后执行二次对账');
    expect(checklist).toContain('daemon/OpenCode 进程检查命令已成功并可解析');
    expect(checklist).toContain('Git porcelain 等机器结构化输出使用原始 bytes 和协议分隔符解析');
    expect(checklist).toContain('引用审计已区分活跃权威依赖');
    expect(checklist).toContain('Git porcelain `M` 已通过规范化 blob');
    expect(checklist).toContain('修改脚本已在首次写入前验证进程');
    expect(checklist).toContain('实施文档重构已同步经验门禁');
    expect(checklist).toContain('每条验证断言已绑定真实生产者');
    expect(checklist).toContain('最终成功证据已与当前状态文档');
    expect(checklist).toContain('源码调用和依赖审计已区分可执行语法');
    expect(checklist).toContain('Runtime已在candidate_preparing→candidate_prepared边界按Classification物化完整Manifest');
    expect(checklist).toContain('Candidate文件和专业Gate要求已逐项绑定正式Classification');
    expect(checklist).toContain('状态名均来自正式状态枚举与迁移表');
    expect(checklist).toContain('专业Agent只通过受控Tool写治理Candidate');
    expect(checklist).toContain('HardStop活动锁与resolution历史已分层取证');
    expect(checklist).toContain('Monorepo单包TypeScript检查前已按正式拓扑生成内部依赖声明');
    expect(checklist).toContain('Gate验证的治理职责已绑定正式治理对象和冻结Manifest');
    expect(checklist).toContain('补丁包Source Contract已由声明HEAD的精确字节生成并逐文件交叉验证');
    expect(checklist).toContain('Candidate Phase与Classification已取交集');
    expect(checklist).toContain('补丁验证已先运行最小A/B基线控制');
    expect(checklist).toContain('PRIOR_FAILURE_RECONCILIATION=PASS');
    expect(checklist).toContain('BACKFILLED_ERROR_IDS');
    expect(checklist).toContain('UNRECORDED_FAILURES=0');
    expect(checklist).toContain('补录完成后重新读取最新版经验文件');
    expect(checklist).toContain('真实cmd.exe无副作用语法烟雾测试');
    expect(checklist).toContain('用户可见下载链接独立完整');
    expect(checklist).toContain('文本锚点匹配数量恰好为1');
    expect(checklist).toContain('未依赖其他工具临时目录');
    expect(checklist).toContain('未根据记忆构造锚点');
    expect(checklist).toContain('UTF-8中文文件进入Windows剪贴板时已显式UTF-8解码、以CF_UNICODETEXT写入并逐字符回读');
  });

  it('records every new error with a class-level prevention rule', () => {
    const document = readFileSync(experiencePath, 'utf-8');
    expect(document).toContain('### ERR-039：经验门禁解析器只读取标题仍报告通过');
    expect(document).toContain('### ERR-040：治理能力升级后历史测试夹具未同步权威契约');
    expect(document).toContain('close_formal_version_gate');
    expect(document).toContain('verification_gate → formal_version_gate');
    expect(document).toContain('verification_report_contract_valid');
    expect(document).toContain('formal_hard_gate_verification_gate_json');
    expect(document).toContain('### ERR-041：补丁包与配套应用脚本来自不同冻结时点');
    expect(document).toContain('### ERR-042：迁移脚本把目标状态要求错误地作为源状态前置条件');
    expect(document).toContain('### ERR-043：验证器把非权威反馈字段的字面值当成文档必备契约');
    expect(document).toContain('### ERR-044：生产错误信息和注释仍描述已废止的双状态权威路径');
    expect(document).toContain('### ERR-045：新测试夹具把兼容读取路径当作正式 Candidate 写入路径');
    expect(document).toContain('## EXP-027：兼容读取路径不能成为新写入捷径');
    expect(document).toContain('### ERR-046：外层一键 CMD 在启动包内脚本前失败但没有反馈');
    expect(document).toContain('## EXP-028：交付入口必须从第一步就可观察');
    expect(document).toContain('### ERR-047：统一测试夹具把审批前与合并后阶段折叠到同一个构造步骤');
    expect(document).toContain('### ERR-048：测试直接调用底层 runGate 绕过正式 Gate 编排与治理叠加');
    expect(document).toContain('## EXP-029：测试必须遵守真实阶段顺序并使用正式编排入口');
    expect(document).toContain('### ERR-049：Close Gate 检查项升级后快速路径豁免消费者仍使用旧 check_id');
    expect(document).toContain('## EXP-030：结构化检查标识是生产者—消费者契约');
    expect(document).toContain('### ERR-050：快速路径规则修复落在可绕过的 Gate Chain，正式 Close Handler 未消费');
    expect(document).toContain('## EXP-031：业务规则必须落在全部生产入口共同消费的责任层');
    expect(document).toContain('### ERR-051：最终验证证据包未包含完整变更内容');
    expect(document).toContain('## EXP-032：最终证据必须使完整变更集可重建、可审查');
    expect(document).toContain('### ERR-052：工程验证通过后当前状态文档仍保留验证前或互相冲突的阶段描述');
    expect(document).toContain('## EXP-033：当前状态文档必须与最终证据在同一阶段收口');
    expect(document).toContain('### ERR-053：状态迁移脚本在识别源状态前先执行目标状态语义门禁');
    expect(document).toContain('## EXP-034：先识别迁移状态，再执行状态专属门禁');
    expect(document).toContain('### ERR-054：状态对账包成功后交接文件仍把本包已完成动作列为下一步');
    expect(document).toContain('## EXP-035：状态对账目标必须描述成功后的下一阶段');
    expect(document).toContain('### ERR-055：经验前置门禁只同步到交接和用户级模板，遗漏仓库根 AGENTS 入口');
    expect(document).toContain('## EXP-036：强制治理规则必须覆盖全部实际入口消费者');
    expect(document).toContain('### ERR-056：包含“待提交”状态的当前文档在提交成功后没有执行提交后对账');
    expect(document).toContain('## EXP-037：提交依赖状态必须通过提交后对账闭环');
    expect(document).toContain('### ERR-057：进程存活检查命令执行失败仍被解释为 daemon 未运行');
    expect(document).toContain('## EXP-038：进程不存在结论必须建立在成功且可解析的进程快照上');
    expect(document).toContain('### ERR-058：Git porcelain 输出被整体裁剪后首个文件路径丢失首字符');
    expect(document).toContain('## EXP-039：机器结构化输出必须先解析，不能先做展示层空白规范化');
    expect(document).toContain('### ERR-059：历史观测日志命中被误判为 Work Item 的正式外部引用');
    expect(document).toContain('## EXP-040：引用审计必须区分活跃权威依赖与不可变历史证据');
    expect(document).toContain('### ERR-060：把内容中性的 Git `M` 状态当成必须通过 index 刷新清除的业务变更');
    expect(document).toContain('## EXP-041：Git 工作区状态必须区分正式内容差异与 stat/index 元数据差异');
    expect(document).toContain('## 22. 2026-08-04 真实环境关闭更新');
    expect(document).toContain('P0-PSV-BINDING-001：CLOSED');
    expect(document).toContain('ERR-060：CLOSED');
    expect(document).toContain('### ERR-061：运行边界前置条件在写入之后检查');
    expect(document).toContain('### ERR-062：精确目标状态在干净工作区要求之后识别，导致失败运行不可重入');
    expect(document).toContain('## EXP-042：可恢复脚本必须先验证零写入前置条件，再识别精确源/目标状态');
    expect(document).toContain('### ERR-063：实施状态文档重构后保留了已经失效的固定文本断言');
    expect(document).toContain('## EXP-043：实施文档重构必须同步全部固定文本消费者');
    expect(document).toContain('### ERR-064：验证器要求生产者契约中不存在的 `trigger_result.project_spec_version`');
    expect(document).toContain('## EXP-044：验证断言必须绑定真实生产者契约和文件职责');
    expect(document).toContain('### ERR-065：最终验证成功后当前交接仍停留在“待验证”状态');
    expect(document).toContain('## EXP-045：成功证据产生后必须执行提交前最终状态对账');
    expect(document).toContain('### ERR-066：源码审计把注释中的 `Bun.file` 文本误判为可执行持久化调用');
    expect(document).toContain('## EXP-046：源码调用证据必须区分可执行语法、注释和普通文本');
    expect(document).toContain('### ERR-067：混合 Candidate 生产者使 Runtime-owned `candidate_manifest` 只保留首个显式条目');
    expect(document).toContain('## EXP-047：多Tool Candidate生产必须在Runtime状态边界收口为完整冻结Manifest');
    expect(document).toContain('### ERR-068：`architecture_change` full Candidate Gate无条件要求未发生变化的 Requirement Candidate');
    expect(document).toContain('## EXP-048：Candidate和Gate要求必须由正式Classification决定');
    expect(document).toContain('### ERR-069：场景文档和提示词使用状态机中不存在的 `gates_passed`');
    expect(document).toContain('## EXP-049：状态名是生产者—消费者契约，文档和提示词不得发明描述性状态');
    expect(document).toContain('### ERR-070：专业设计Agent在受控Candidate写入阶段调用 `sf_safe_bash`');
    expect(document).toContain('## EXP-050：专业Agent的治理产物写入必须走精确受控Tool边界');
    expect(document).toContain('### ERR-071：把已恢复HardStop的活动锁文件当作永久历史证据');
    expect(document).toContain('## EXP-051：活动锁、恢复历史和独立修复前置条件必须分层');
    expect(document).toContain('### ERR-072：在内部依赖声明生成前执行daemon-core TypeScript检查，并遗漏可选工作流路径类型');
    expect(document).toContain('## EXP-052：Monorepo TypeScript验证必须先准备内部声明，并分离环境错误与代码错误');
    expect(document).toContain('### ERR-073：V31由Python直接启动Windows npm Bun包装器导致安装器未启动');
    expect(document).toContain('### ERR-074：V32把无扩展名POSIX Bun shim误当成Win32可执行文件');
    expect(document).toContain('### ERR-075：Design Gate要求模块Design承载系统治理，但Write Guard禁止该模块投影使用system_governance');
    expect(document).toContain('### ERR-076：V34声明a0333ba基线却使用提交前旧临时树生成Source Contract');
    expect(document).toContain('## EXP-053：Gate必须按正式治理对象职责消费冻结Manifest，不能要求下层产物复制上层责任');
    expect(document).toContain('## EXP-054：补丁Source Contract必须由声明HEAD的精确字节生成并逐文件交叉验证');
    expect(document).toContain('### ERR-077：V35新增测试把不受当前运行器支持的非对称匹配器嵌入数组深比较');
    expect(document).toContain('### ERR-078：Classification驱动Gate忽略Candidate Phase，Design阶段提前要求Requirement');
    expect(document).toContain('### ERR-079：回归测试把文件末尾换行计算为额外逻辑行并形成基线假失败');
    expect(document).toContain('## EXP-055：关键测试断言必须以实际运行器支持的组合表达');
    expect(document).toContain('## EXP-056：Candidate Phase与Classification必须取交集，不能互相替代');
    expect(document).toContain('## EXP-057：补丁验证必须先做最小A/B基线归因，文本度量必须排除格式尾项');
    expect(document).toContain('### ERR-080：经验门禁仍断言上一轮临时状态，与同一经验台账的当前状态块冲突');
    expect(document).toContain('## EXP-058：状态型固定文本消费者必须与最终状态块原子同步');
    expect(document).toContain('### ERR-081：生成状态文档时保留额外EOF空行，导致git diff --check阻断完整验证');
    expect(document).toContain('## EXP-059：生成文本文件必须以字节级单一EOF换行契约收口');
    expect(document).toContain('### ERR-082：首个证据收集批处理使用错误换行和复杂CMD组合语法，脚本未进入有效执行');
    expect(document).toContain('### ERR-083：多轮压缩包交付链接缺失或被其他标记污染，用户无法下载已生成文件');
    expect(document).toContain('### ERR-084：V37包生成器使用脆弱的整段文本锚点，两次因锚点不存在而中断');
    expect(document).toContain('### ERR-085：修改前门禁只要求读取已有经验，没有强制先补录上一轮和历史遗漏失败');
    expect(document).toContain('### ERR-086：V39生成器假定其他工具的临时解压目录存在，跨运行环境后立即失败');
    expect(document).toContain('### ERR-087：V39生成器按记忆使用不存在的经验检查表固定句，结构定位前置失败');
    expect(document).toContain('## EXP-060：每轮修改必须先补录全部既往失败，再重读最新版经验并执行重复错误检查');
    expect(document).toContain('## EXP-061：Windows CMD/BAT交付必须通过真实解析器、编码和换行契约验证');
    expect(document).toContain('## EXP-062：文件生成成功不等于交付成功，下载链接必须独立验证');
    expect(document).toContain('## EXP-063：补丁生成器必须使用结构化边界或受控锚点，禁止盲目整段替换');
    expect(document).toContain('## EXP-064：生成器必须从当前环境已验证输入自举，禁止依赖跨工具临时目录');
    expect(document).toContain('## EXP-065：修改脚本必须先读取当前目标结构，禁止根据记忆构造锚点');
    expect(document).toContain('### ERR-088：共享章节匹配器只支持直接括号后缀，真实Project Architecture标题被误判为缺失');
    expect(document).toContain('### ERR-089：V44标题后缀正则使用跨行空白，把下一行首条证据误吞为标题说明');
    expect(document).toContain('### ERR-090：V44两个固定文本测试未与最终状态生产者原子同步');
    expect(document).toContain('### ERR-091：固定文本测试把字面量反斜杠t解释为真实制表符');
    expect(document).toContain('### ERR-092：Bun测试环境中的String.raw把中文模板内容暴露为Unicode转义字面量');
    expect(document).toContain('## EXP-066：解析器回归必须使用真实项目原始格式，并同时验证正向兼容与反向拒绝');
    expect(document).toContain('## EXP-067：Markdown标题匹配必须是物理单行语法，标题空白不得使用可跨行的 `\\s`');
    expect(document).toContain('## EXP-068：固定文本测试必须断言正式生产者字段，不得断言未写入文档的概括');
    expect(document).toContain('## EXP-069：固定文本测试必须明确区分源文本转义与运行时字符');
    expect(document).toContain('## EXP-070：非ASCII固定文本不得默认使用String.raw');
    expect(document).toContain('### ERR-093：正式Gate重验提示要求文件哈希，主编排代理在只读受限状态调用sf_safe_bash触发可避免HardStop');
    expect(document).toContain('### ERR-094：远程源码调查首选git clone因执行环境DNS失败，必须切换官方直链并保留取证来源');
    expect(document).toContain('## EXP-071：受限状态的只读证据不能通过sf_safe_bash补哈希');
    expect(document).toContain('## EXP-072：远程源码调查必须支持固定commit的官方直链回退');
    expect(document).toContain('ERR-093=CLOSED');
    expect(document).toContain('ERR-094=CLOSED_V52_OFFICIAL_SOURCE_FALLBACK');
    expect(document).toContain('### ERR-095：V52验证器把HardStop语义事实绑定到一手日志中不存在的人工合成字段');
    expect(document).toContain('## EXP-073：一手运行日志按语义事实组合验真，不得依赖后加汇总字段');
    expect(document).toContain('ERR-095=CLOSED');
    expect(document).toContain('### ERR-096：旧HardStop测试仍把work_item.status当作必填字段，与当前元数据契约冲突');
    expect(document).toContain('## EXP-074：基线测试失败必须区分产品回归与测试消费者漂移');
    expect(document).toContain('ERR-096=CLOSED');
    expect(document).toContain('### ERR-097：V54基线验证器写死无关通过数量49，正确的精确失败集合被再次误判');
    expect(document).toContain('## EXP-075：已知失败验证必须比较失败集合，不得猜测无关pass数量');
    expect(document).toContain('ERR-097=CLOSED');
    expect(document).toContain('### ERR-098：V55封包静态审计全文件禁止49 pass，误伤必须保留的V54失败对账证据');
    expect(document).toContain('## EXP-076：静态审计必须限定语义作用域，不能禁止历史证据中的同名字符串');
    expect(document).toContain('ERR-098=CLOSED_V55_PACKAGE_PREFLIGHT_CORRECTED');
    expect(document).toContain('### ERR-099：V55成功摘要仍使用V52旧常量，报告7文件和ERR-093/094但实际证据为8文件和ERR-093—098');
    expect(document).toContain('## EXP-077：验证结果摘要必须由Manifest和实际集合派生，禁止重复维护范围常量');
    expect(document).toContain('ERR-099=CLOSED');
    expect(document).toContain('### ERR-100：V56证据对账函数使用re.findall但验证器没有模块级导入re');
    expect(document).toContain('## EXP-078：验证器封包前必须执行关键函数，compile不能证明运行时依赖完整');
    expect(document).toContain('ERR-100=CLOSED');
    expect(document).toContain('### ERR-101：V57成功摘要的适用经验规则仍使用旧硬编码，遗漏EXP-077与EXP-078');
    expect(document).toContain('## EXP-079：prior_failure_reconciliation必须整体从Manifest派生，不能只修正部分字段');
    expect(document).toContain('ERR-101=CLOSED');
    expect(document).toContain('### ERR-102：V59最终ZIP包含运行时生成的pyc，包内文件与Manifest大小及SHA256不一致');
    expect(document).toContain('## EXP-080：最终交付ZIP必须排除运行时缓存并在成包后重开核验');
    expect(document).toContain('ERR-102=CLOSED');
    expect(document).toContain('### ERR-103：V60已知失败集合解析未剥离Bun耗时后缀，正确ERR-096基线再次被误判');
    expect(document).toContain('## EXP-081：测试失败身份必须剥离非语义运行时装饰后再做精确集合比较');
    expect(document).toContain('ERR-103=CLOSED');
    expect(document).toContain('### ERR-104：V61远程HEAD预检因Windows Git schannel TLS握手失败而停止');
    expect(document).toContain('## EXP-082：远程Git TLS环境失败必须保留证据并使用官方独立入口回退');
    expect(document).toContain('ERR-104=CLOSED');
    expect(document).toContain('### ERR-105：V62封包前py_compile再次生成__pycache__并被Manifest预检阻断');
    expect(document).toContain('## EXP-083：封包期Python检查必须以零字节码产生为执行合同');
    expect(document).toContain('ERR-105=CLOSED');
    expect(document).toContain('### ERR-106：V63用户级验证器把Manifest的files对象误判为列表，成功升级被报告为files=None');
    expect(document).toContain('## EXP-084：Manifest集合形状必须由生产者Schema和真实产物确定');
    expect(document).toContain('ERR-106=CLOSED');
    expect(document).toContain('### ERR-107：V63升级成功后未立即记录动作状态，失败摘要误报REAL_INSTALL_ACTION=NOT_PERFORMED');
    expect(document).toContain('## EXP-085：有副作用动作成功后必须立即固化动作事实');
    expect(document).toContain('ERR-107=CLOSED');
    expect(document).toContain('### ERR-108：V64子任务关闭状态被无作用域地写成当前任务关闭，并把P0未完成状态错误投影为可进入下一阶段');
    expect(document).toContain('## EXP-086：子任务关闭不能覆盖父阶段生命周期');
    expect(document).toContain('ERR-108=CLOSED');
    expect(document).toContain('### ERR-109：V65修改状态生产者后遗漏两个既有固定文本消费者，正确状态被旧CURRENT_TASK_STATUS断言阻断');
    expect(document).toContain('## EXP-087：状态生产者变更必须先完成全消费者清单再冻结范围');
    expect(document).toContain('ERR-109=CLOSED');

    expect(document).toContain('ERR-088=CLOSED_V51_WORKDESK_REAL_RETEST');
    expect(document).toContain('ERR-089=CLOSED_V50_COMMITTED_PUSHED');
    expect(document).toContain('ERR-090=CLOSED_V50_COMMITTED_PUSHED');
    expect(document).toContain('ERR-091=CLOSED_V50_COMMITTED_PUSHED');
    expect(document).toContain('ERR-092=CLOSED_V50_COMMITTED_PUSHED');
    expect(document).toContain('ERR-081=CLOSED_V38_ISOLATED_VALIDATED');
    expect(document).toContain('ERR-082=CLOSED_V42_COMMITTED_PUSHED');
    expect(document).toContain('ERR-083=CLOSED_V42_COMMITTED_PUSHED');
    expect(document).toContain('ERR-084=CLOSED_V42_COMMITTED_PUSHED');
    expect(document).toContain('ERR-085=CLOSED_V42_COMMITTED_PUSHED');
    expect(document).toContain('ERR-086=CLOSED_V42_COMMITTED_PUSHED');
    expect(document).toContain('ERR-087=CLOSED_V42_COMMITTED_PUSHED');
    expect(document).toContain('ERR-077=CLOSED_V38_ISOLATED_VALIDATED');
    expect(document).toContain('ERR-078=CLOSED_WORKDESK_REAL_RETEST');
    expect(document).toContain('ERR-079=CLOSED_V38_ISOLATED_VALIDATED');
    expect(document).toContain('ERR-080=CLOSED_V38_ISOLATED_VALIDATED');
    expect(document).toContain('ERR-075=CLOSED_V51_WORKDESK_REAL_RETEST');
    expect(document).toContain('ERR-076=CLOSED_V35_SOURCE_CONTRACT_VALIDATED');
    expect(document).toContain('ERR-064：CLOSED');
    expect(document).toContain('## EXP-032：最终证据必须使完整变更集可重建、可审查');
    expect(document).toContain('一个错误必须产生一个类防护');
  });

  it('requires every delivery round to use one complete downloadable bundle', () => {
    const handoff = readFileSync(currentHandoffPath, 'utf-8');
    const experience = readFileSync(experiencePath, 'utf-8');
    const psvImplementation = readFileSync(psvImplementationPath, 'utf-8');
    const p0ContractClosure = readFileSync(p0ContractClosurePath, 'utf-8');
    const rootAgents = readFileSync(rootAgentsPath, 'utf-8');
    const userLevelAgents = readFileSync(userLevelAgentsPath, 'utf-8');

    expect(handoff).toContain('同一轮只允许一次下载');
    expect(handoff).toContain('### 0.1 上一轮失败补录与本轮经验重读门禁');
    expect(handoff).toContain('PRIOR_FAILURE_RECONCILIATION=PASS');
    expect(handoff).toContain('BACKFILLED_ERROR_IDS=ERR-...或NONE');
    expect(handoff).toContain('UNRECORDED_FAILURES=0');
    expect(handoff).toContain('失败后不得直接重试、改版本号或重新打包');
    expect(handoff).toContain('ERR-082=证据收集CMD换行和组合语法失败');
    expect(handoff).toContain('ERR-087=生成器按记忆使用不存在的旧锚点');
    expect(handoff).toContain('## V39/V40成功与V41提交前状态闭包（2026-08-04）');
    expect(handoff).toContain('V40_PATCH_ACTION_REAL_REPOSITORY=APPLIED_11_OF_11');
    expect(handoff).toContain('V40_FINAL_SCOPE=PASS_EXACT_11_FILES');
    expect(handoff).toContain('V41成功后下一步才是提交和推送');
    expect(handoff).toContain('## V42提交推送闭包与下一阶段边界（2026-08-04）');
    expect(handoff).toContain('COMMIT_ACTION=COMMITTED_EXACT_11_FILES');
    expect(handoff).toContain('PUSH_ACTION=PUSHED_MAIN');
    expect(handoff).toContain('本文件不写入包含自身内容的提交SHA');
    expect(handoff).toContain('用户级安装升级与119/119一致性验证');
    expect(handoff).toContain('WorkDesk重验期间禁止修改Candidate内容');
    expect(handoff).toContain('用户只下载一个完整压缩包');
    expect(handoff).toContain('scripts/apply.py');
    expect(handoff).toContain('scripts/validate.py');
    expect(handoff).toContain('不得在应用成功后再要求用户第二次下载验证文件');
    expect(handoff).toContain('只能包含预期的仓库替换文件');
    expect(handoff).toContain('本轮已验证实现提交');
    expect(handoff).toContain('main@95befe8b35812aeb09e4d9e68f4497e12b3ac2a9');
    expect(handoff).toContain('当前远程 HEAD：每次新会话实时读取');
    expect(handoff).toContain('用户级安装升级：完成');
    expect(handoff).toContain('安装 Manifest、Tool、Skill、Agent 与源码一致性：119/119');
    expect(handoff).toContain('WI-0003 字面引用总数：109');
    expect(handoff).toContain('Project Spec / Module Design / Contract / Trace / 其他 WI 正式引用：0');
    expect(handoff).toContain('WI-0003 Runtime状态：workflow_selected');
    expect(handoff).toContain('当前分配器下一编号：WI-0004');
    expect(handoff).toContain('WI-0003：workflow_selected → superseded');
    expect(handoff).toContain('WI-0004 candidate_manifest.base_spec_version：PSV-0002');
    expect(handoff).toContain('P0-PSV-BINDING-001：CLOSED_REAL_PROJECT_VALIDATED');
    expect(handoff).toContain('V19 辅助脚本执行事实');
    expect(handoff).toContain('拒绝自身5文件精确目标状态');
    expect(handoff).toContain('V20 必须从精确V19目标状态继续验证');
    expect(handoff).toContain('V20 经验门禁失败事实');
    expect(handoff).toContain('V21 从精确V20目标状态继续');
    expect(handoff).toContain('V21 验证执行事实');
    expect(handoff).toContain('WI-0004 trigger_result：符合真实生产者skeleton');
    expect(handoff).toContain('V22 最终验证事实');
    expect(handoff).toContain('场景准备结论：READY_FOR_CONTRACT_CONSUMER_SCENARIO_DESIGN');
    expect(handoff).toContain('V23 提交前最终状态对账');
    expect(handoff).toContain('V24 WorkDesk源码与Contract基线审计事实');
    expect(handoff).toContain('辅助取证脚本误报');
    expect(handoff).toContain('场景名称：WorkItemStatus Project Contract同ID规范化与正式Trace激活');
    expect(handoff).toContain('WI-0005：WorkItemStatus破坏性变更/删除阻断');
    expect(handoff).toContain('WI-0006：ReportFormatter正式Module→Project Promotion');
    expect(handoff).toContain('WI-0004 Phase 1真实运行结果');
    expect(handoff).toContain('Runtime最终状态：gates_failed');
    expect(handoff).toContain('ERR-067：混合Candidate生产者导致Runtime Manifest缺项');
    expect(handoff).toContain('ERR-068：Candidate Gate不按Classification要求产物');
    expect(handoff).toContain('ERR-069：V25提示词和文档使用不存在的gates_passed状态');
    expect(handoff).toContain('ERR-070：sf-design仍调用sf_safe_bash写治理产物并触发可避免HardStop');
    expect(handoff).toContain('Runtime在candidate_preparing→candidate_prepared边界按Classification物化完整Manifest');
    expect(handoff).toContain('V26成功后的下一项完整工作');
    expect(handoff).toContain('## V26实际执行结果与V27隔离验证边界（2026-08-04）');
    expect(handoff).toContain('PATCH_FILES_APPLIED=0/13');
    expect(handoff).toContain('## V27失败结果与V28隔离验证边界（2026-08-04）');
    expect(handoff).toContain('V27定向测试：73/73通过');
    expect(handoff).toContain('## V28—V33完成事实与WI-0004当前冻结状态（2026-08-04）');
    expect(handoff).toContain('当前实现提交=a0333ba56854b26780960823b25db2faf67f080f');
    expect(handoff).toContain('Runtime在candidate_preparing→candidate_prepared自动物化5项Manifest');
    expect(handoff).toContain('WI-0004当前状态=candidate_preparing');
    expect(handoff).toContain('新的真实阻断为 `ERR-075`');
    expect(handoff).toContain('## V34失败与V35隔离验证边界（2026-08-04）');
    expect(handoff).toContain('实际P0文件SHA256=094a08e41c74b418907d98757594833d8988dc24916c4df9f5c837509159d6af');
    expect(handoff).toContain('GOV-DEFECT-CONTRACT-CONSUMER-001 仍保持 IN_PROGRESS');
    expect(handoff).toContain('`STAT_ONLY_CONTENT_NEUTRAL`');
    expect(handoff).toContain('WorkDesk文件和index保持原状');
    expect(handoff).toContain('## V63真实提交、用户级升级成功与ERR-106—ERR-107状态闭包（2026-08-05）');
    expect(handoff).toContain('V63_COMMIT_SHA=688cf64c6e190a707f9f0e7306db5cf474f0ae35');
    expect(handoff).toContain('V63_VALIDATOR_EXPECTED_FILES_TYPE=list');
    expect(handoff).toContain('V63_ACTUAL_FILES_TYPE=object');
    expect(handoff).toContain('ERR106_STATUS=CLOSED');
    expect(handoff).toContain('ERR107_STATUS=CLOSED');
    expect(handoff).toContain('V63_USERLEVEL_UPGRADE=CONFIRMED_SUCCESS');
    expect(handoff).toContain('V64_TASK_STATUS=CLOSED');
    expect(handoff).toContain('P0_OVERALL_STATUS=IN_PROGRESS');
    expect(handoff).toContain('P1_ACTION=NOT_STARTED');
    expect(handoff).toContain('NEXT_ACTION=RESOLVE_P0_CONTINUATION_BOUNDARY_BEFORE_P1');
    expect(handoff).toContain('P0_CONTINUATION_BOUNDARY=ISOLATED_REAL_PROJECT');
    expect(handoff).toContain(
      'P0_VALIDATION_PROJECT=D:\\code\\temp\\SpecForge-P0-Validation',
    );
    expect(handoff).toContain('WORKDESK_WI0004_ACTION=NONE');
    expect(handoff).toContain(
      'NEXT_ACTION=USER_MANUALLY_OPEN_OPENCODE_AND_PASTE_VERIFIED_UNICODE_WI0001',
    );
    expect(handoff).toContain(
      'P0_VALIDATION_PROJECT_RELATION_TO_PHASE11=NOT_PHASE11_EVIDENCE',
    );
    expect(handoff).toContain('## V68封包前ERR-113闭包（2026-08-05）');
    expect(handoff).toContain('ERR-113_REGRESSION=PURE_ESM_IMPORT_AND_DIRECT_CLI_BOTH_PASS');
    expect(experience).toContain('### ERR-113：V68独立项目种子CLI入口判断假定process.argv[1]必然存在，纯模块导入在封包前失败');
    expect(experience).toContain('## EXP-090：CLI可执行入口必须允许模块被无副作用导入');
    expect(experience).toContain('ERR-113=CLOSED');
    expect(handoff).toContain('## V68封包前ERR-114闭包（2026-08-05）');
    expect(handoff).toContain('ERR-114_REGRESSION=TYPESCRIPT_PROGRAM_UNDEFINED_IDENTIFIER_CHECK_PASS');
    expect(experience).toContain('### ERR-114：V68新增ERR-113测试断言错误引用另一测试块局部变量，语法转译通过但语义作用域无效');
    expect(experience).toContain('## EXP-091：测试断言必须与其局部证据生产者处于同一语义作用域');
    expect(experience).toContain('ERR-114=CLOSED');
    expect(experience).toContain('### ERR-115：使用CMD的type管道把UTF-8中文提示词写入clip，OpenCode粘贴结果乱码');
    expect(experience).toContain('## EXP-092：跨编码边界必须显式解码、使用Unicode协议并完成真实往返');
    expect(experience).toContain('ERR-115=CLOSED');
    expect(experience).toContain('### ERR-117：V70目标状态生产者已切换但两个固定文本测试仍要求V69状态字面值');
    expect(experience).toContain('## EXP-094：生命周期状态必须稳定，尝试版本只属于证据');
    expect(experience).toContain('ERR-117=CLOSED');
    expect(experience).toContain('### ERR-118：新模块完整候选被 Runtime 自己排除后又被 Gate 强制要求');
    expect(experience).toContain('### ERR-119：project_contract_changed没有进入Project Contract Candidate物化条件');
    expect(experience).toContain('### ERR-120：专业Agent在Candidate修订后使用sf_safe_bash验证治理目录并触发HardStop');
    expect(experience).toContain('## EXP-095：新模块Candidate完整性必须由同一个Runtime规则生产并由Gate消费');
    expect(experience).toContain('## EXP-096：每个正式Classification字段必须完成生产者—全部消费者清单');
    expect(experience).toContain('## EXP-097：专业Agent的受控工具边界必须进入每次委派任务');
    expect(experience).toContain('### ERR-121：V72治理文档结尾多出空白行被git diff --check阻断');
    expect(experience).toContain('## EXP-098：文档追加后必须在目标字节冻结前规范单个LF结尾');
    expect(experience).toContain('### ERR-122：固定文本测试把第二个期望值误作toContain提示参数');
    expect(experience).toContain('## EXP-099：断言API的可选参数不得承载第二个业务事实');
    expect(experience).toContain('### ERR-123：V72使用Python shell=False直接启动Bun shim，隔离依赖阶段发生FileNotFoundError');
    expect(experience).toContain('## EXP-100：Windows命令shim必须通过其所属命令解释器启动并先做真实入口预检');
    expect(experience).toContain('### ERR-124：V73在workspace类型声明生成前运行daemon-core TypeScript检查');
    expect(experience).toContain('## EXP-101：workspace类型消费者必须在声明生产者构建后验证');
    expect(handoff).toContain('## V65测试消费者漂移与V66闭包边界（2026-08-05）');
    expect(handoff).not.toMatch(/ERR-?11[5-7](?:_STATUS)?=CLOSED_AFTER_V\d+/);
    expect(handoff).not.toMatch(/NEXT_ACTION=.*PASTE_V\d+_VERIFIED_UNICODE_WI0001/);
    expect(handoff).not.toMatch(/^CURRENT_TASK_STATUS=CLOSED\s*$/m);
    expect(handoff).not.toMatch(/^NEXT_ACTION=START_NEXT_AUTHORITY_PHASE_ONLY_AFTER_NEW_IMPACT_ANALYSIS\s*$/m);
    expect(handoff).not.toContain('刷新 WorkDesk Git index 中4个字节未变文件的 stat 状态');
    expect(handoff).not.toContain('核对用户级 SpecForge 安装来源与当前版本');
    expect(handoff).not.toContain('用户暂存、提交并推送当前 19 文件变更');
    expect(handoff).not.toContain('完成当前状态文档同步并复跑同一验证集');
    expect(psvImplementation).toContain('`CLOSED_REAL_PROJECT_VALIDATED`');
    expect(psvImplementation).toContain('## WorkDesk Real-Project Validation Evidence');
    expect(psvImplementation).toContain('allocated as `WI-0004`;');
    expect(psvImplementation).toContain('defect `P0-PSV-BINDING-001` is closed');
    expect(psvImplementation).toContain('9. [x] Transition WI-0003');
    expect(psvImplementation).toContain('10. [x] Create the next Work Item');
    expect(psvImplementation).toContain('must not require a clean porcelain display');
    expect(psvImplementation).toContain('`95befe8b35812aeb09e4d9e68f4497e12b3ac2a9`');
    expect(psvImplementation).toContain('6. [x] Commit the validated change set');
    expect(psvImplementation).toContain('7. [x] Upgrade the user-level SpecForge runtime');
    expect(psvImplementation).not.toContain('remains uncommitted');
    expect(p0ContractClosure).toContain('> **状态**：IN_PROGRESS');
    expect(p0ContractClosure).toContain('### 25.5 WorkDesk 真实创建链验证');
    expect(p0ContractClosure).toContain('WI-0004 candidate_manifest.base_spec_version：PSV-0002');
    expect(p0ContractClosure).toContain('INSUFFICIENT_EVIDENCE：真实业务项目中的 Project Contract 新增和多个DD消费者尚未端到端验证');
    expect(p0ContractClosure).toContain('### 25.7 下一验证边界');
    expect(p0ContractClosure).toContain('### 25.8 V24 WorkDesk源码与Contract基线审计');
    expect(p0ContractClosure).toContain('### 25.9 WI-0004 第一阶段真实场景冻结');
    expect(p0ContractClosure).toContain('ADD DD-CLI-002 constrained_by WorkItemStatus');
    expect(p0ContractClosure).toContain('到 `approval_required` 必须停止');
    expect(p0ContractClosure).toContain('### 25.10 WI-0004 Phase 1真实运行结果');
    expect(p0ContractClosure).toContain('### 25.11 修复设计');
    expect(p0ContractClosure).toContain('### 25.12 修复后恢复边界');
    expect(p0ContractClosure).toContain('### 25.13 V26产品修复与工程验证边界');
    expect(p0ContractClosure).toContain('Runtime在candidate_preparing→candidate_prepared物化Manifest');
    expect(p0ContractClosure).toContain('### 25.14 V26零写入失败与V27隔离验证修正');
    expect(p0ContractClosure).toContain('WorkDesk只读审计不再作为源码修复的因果前置');
    expect(p0ContractClosure).toContain('### 25.15 V27类型检查失败与V28验证顺序修正');
    expect(p0ContractClosure).toContain('V27定向测试73/73通过');
    expect(p0ContractClosure).toContain('### 25.16 V28—V33产品修复、提交与安装结果');
    expect(p0ContractClosure).toContain('### 25.17 WI-0004 Manifest、Classification与工具边界真实重测');
    expect(p0ContractClosure).toContain('### 25.18 ERR-075系统治理载体责任冲突与V34边界');
    expect(p0ContractClosure).toContain('### 25.24 V39/V40成功与V41提交前状态闭包');
    expect(p0ContractClosure).toContain('V40真实仓库应用均已成功');
    expect(p0ContractClosure).toContain('V41不改变产品代码');
    expect(p0ContractClosure).toContain('### 25.25 V42提交推送闭包与用户级升级边界');
    expect(p0ContractClosure).toContain('提交文件=精确11个');
    expect(p0ContractClosure).toContain('提交SHA不能写入包含自身内容的提交文件');
    expect(p0ContractClosure).toContain('待用户级安装和WorkDesk真实重验');
    expect(p0ContractClosure).toContain('### 25.19 V34源基线哈希错误与V35隔离验证边界');
    expect(p0ContractClosure).toContain('WI-0004当前冻结在 `candidate_preparing`');
    expect(p0ContractClosure).toContain('### 25.44 ERR-106—ERR-107用户级Manifest Schema与动作证据闭包');
    expect(p0ContractClosure).toContain('### 25.45 V64后P0父阶段与子任务状态对账');
    expect(p0ContractClosure).toContain('### 25.46 ERR-109状态生产者与固定文本消费者原子同步');
    expect(p0ContractClosure).toContain('specforge-manifest.json files对象精确119项');
    expect(p0ContractClosure).toContain('动作状态与后续验证状态分别报告');
    expect(p0ContractClosure).not.toContain('到 `gates_passed` 必须停止');

    for (const entry of [rootAgents, userLevelAgents]) {
      expect(entry).toContain('docs/rule/specforge-development-error-ledger-and-experience.md');
      expect(entry).toContain('EXPERIENCE_FILE_READ=YES');
      expect(entry).toContain('APPLICABLE_EXPERIENCE_RULES');
      expect(entry).toContain('REPEATED_ERROR_CHECK=PASS');
    }
  });


  it('uses an explicit Windows Unicode clipboard transport for UTF-8 prompts', () => {
    const cmd = readFileSync(unicodeClipboardCmdPath, 'utf-8');
    const python = readFileSync(unicodeClipboardPythonPath, 'utf-8');
    const handoff = readFileSync(currentHandoffPath, 'utf-8');
    const p0 = readFileSync(p0ContractClosurePath, 'utf-8');

    expect(cmd).toContain('copy-utf8-to-clipboard.py');
    expect(cmd).not.toMatch(/\btype\b[^\r\n]*\|\s*clip/i);
    expect(cmd).not.toMatch(/\bchcp\b/i);
    expect(cmd).not.toMatch(/powershell/i);
    expect(python).toContain('decode("utf-8-sig")');
    expect(python).toContain('CF_UNICODETEXT = 13');
    expect(python).toContain('SetClipboardData(CF_UNICODETEXT, handle)');
    expect(python).toContain('GetClipboardData(CF_UNICODETEXT)');
    expect(python).toContain('if actual != expected:');
    expect(python).toContain('CLIPBOARD_UNICODE_ROUNDTRIP=PASS');
    const experience = readFileSync(experiencePath, 'utf-8');
    expect(experience).toContain('### ERR-116：V69把含嵌套双引号的call命令作为cmd.exe /c参数');
    expect(experience).toContain('## EXP-093：cmd.exe /c不得通过跨运行时参数序列化承载含嵌套引号的完整命令');
    expect(handoff).toContain('## V68成功与ERR-115 Windows Unicode剪贴板闭包（2026-08-05）');
    expect(handoff).toContain('WI0001_ACTION=NOT_PERFORMED');
    expect(handoff).toContain('NEXT_ACTION=USER_MANUALLY_OPEN_OPENCODE_AND_PASTE_VERIFIED_UNICODE_WI0001');
    expect(handoff).toContain('## WI-0001真实Gate阻断、ERR-118—ERR-120与Runtime修复边界（2026-08-05）');
    expect(handoff).toContain('WI0001_GATE_RESULT=9_OF_10');
    expect(handoff).toContain('NEXT_ACTION=VALIDATE_COMMIT_DEPLOY_THEN_RESUME_WI0001_ONCE');
    expect(handoff).toContain('## V72 Bun入口失败、ERR-123与V73验证器闭包边界（2026-08-05）');
    expect(handoff).toContain('## V73工作区类型声明顺序失败、ERR-124与V74验证器闭包边界（2026-08-05）');
    expect(p0).toContain('### 25.52 V68成功与ERR-115 Windows Unicode提示词传输边界');
    expect(handoff).toContain('## V69失败、ERR-116与V70 CMD包装调用闭包（2026-08-05）');
    expect(handoff).toContain('ERR116_STATUS=CLOSED');
    expect(handoff).toContain('ERR117_STATUS=CLOSED');
    expect(handoff).toContain('V70_FAILURE_RECONCILIATION=PASS_TEST_DRIFT_EXACT_2');
    expect(p0).toContain('### 25.53 V69 CMD脚本调用假失败与ERR-116验证器闭包');
  });

});
