/**
 * Default ServiceUnitGenerator Implementation
 *
 * Generates:
 * - systemd unit files for Linux
 * - NSSM command sequences for Windows
 */

import type { ServiceInstallSpec } from "../types/service-install-spec.js";
import type { ServiceUnitMetadata } from "../types/service-unit-metadata.js";
import type { NssmCommand } from "../types/nssm-command.js";
import type { ServiceUnitGenerator } from "./service-unit-generator.js";

/**
 * Default implementation of ServiceUnitGenerator
 */
export class DefaultServiceUnitGenerator implements ServiceUnitGenerator {
  private readonly packageName = "@specforge/service-management";
  private readonly packageVersion: string;

  constructor(packageVersion: string) {
    this.packageVersion = packageVersion;
  }

  /**
   * Generate systemd unit file text
   */
  generateSystemdUnit(spec: ServiceInstallSpec): string {
    const now = new Date().toISOString();
    const metadata = [
      "# === GENERATED BY SPECFORGE — DO NOT EDIT MANUALLY ===",
      `# schema_version: 1.0`,
      `# generated-by: ${this.packageName}@${this.packageVersion}`,
      `# generated-at: ${now}`,
      `# specforge-version: ${this.packageVersion}`,
      `# service-name: ${spec.name}`,
      `# binary-path: ${spec.binaryPath}`,
      "# === END METADATA ===",
      "",
    ].join("\n");

    // Build [Unit] section
    const unitSection = [
      "[Unit]",
      `Description=${spec.description}`,
      `Documentation=https://github.com/specforge/specforge`,
      ...this.renderDependencies(spec.dependsOn),
      "",
    ].join("\n");

    // Build [Service] section
    const serviceSection = [
      "[Service]",
      "Type=simple",
      `ExecStart=${spec.binaryPath}${spec.args.length > 0 ? " " + spec.args.join(" ") : ""}`,
      `Restart=${spec.restartPolicy === "on-failure" ? "on-failure" : spec.restartPolicy === "always" ? "always" : "no"}`,
      "RestartSec=5s",
      "KillSignal=SIGTERM",
      "TimeoutStopSec=10",
      `StandardOutput=append:${spec.stdoutLogPath}`,
      `StandardError=append:${spec.stderrLogPath}`,
      ...this.renderEnvironment(spec.environment),
      "",
    ].join("\n");

    // Build [Install] section
    const installSection = "[Install]\nWantedBy=default.target";

    return [metadata, unitSection, serviceSection, installSection].join("\n");
  }

  /**
   * Generate NSSM command sequence for Windows
   */
  generateNssmCommands(spec: ServiceInstallSpec, nssmExePath: string): NssmCommand[] {
    const commands: NssmCommand[] = [];

    // 1. Install the service
    commands.push({
      subcommand: "install",
      args: [
        spec.name,
        spec.binaryPath,
        ...spec.args,
      ],
      allowFailure: false, // install should succeed or fail clearly
    });

    // 2. Set AppDirectory
    commands.push({
      subcommand: "set",
      args: ["AppDirectory", spec.workingDirectory],
      allowFailure: true, // idempotent
    });

    // 3. Set AppEnvironmentExtra
    const envEntries = Object.entries(spec.environment).map(
      ([key, value]) => `${key}=${value}`
    );
    if (envEntries.length > 0) {
      commands.push({
        subcommand: "set",
        args: ["AppEnvironmentExtra", ...envEntries],
        allowFailure: true, // idempotent
      });
    }

    // 4. Set Start SERVICE_AUTO_START
    commands.push({
      subcommand: "set",
      args: ["Start", "SERVICE_AUTO_START"],
      allowFailure: true, // idempotent
    });

    // 5. Set DependOnService
    if (spec.dependsOn.length > 0) {
      commands.push({
        subcommand: "set",
        args: ["DependOnService", ...spec.dependsOn],
        allowFailure: true, // idempotent
      });
    }

    // 6. Set AppStdout
    commands.push({
      subcommand: "set",
      args: ["AppStdout", spec.stdoutLogPath],
      allowFailure: true, // idempotent
    });

    // 7. Set AppStderr
    commands.push({
      subcommand: "set",
      args: ["AppStderr", spec.stderrLogPath],
      allowFailure: true, // idempotent
    });

    // 8. Set AppExit Default Restart
    commands.push({
      subcommand: "set",
      args: ["AppExit", "Default", "Restart"],
      allowFailure: true, // idempotent
    });

    // 9. Set AppRestartDelay 5000
    commands.push({
      subcommand: "set",
      args: ["AppRestartDelay", "5000"],
      allowFailure: true, // idempotent
    });

    // 10. Set AppStopMethodSkip 0
    commands.push({
      subcommand: "set",
      args: ["AppStopMethodSkip", "0"],
      allowFailure: true, // idempotent
    });

    return commands;
  }

  /**
   * Parse metadata from unit file content
   */
  parseMetadata(unitContent: string): ServiceUnitMetadata | null {
    try {
      // Find metadata block
      const startMarker = "# === GENERATED BY SPECFORGE — DO NOT EDIT MANUALLY ===";
      const endMarker = "# === END METADATA ===";

      const startIndex = unitContent.indexOf(startMarker);
      const endIndex = unitContent.indexOf(endMarker);

      if (startIndex === -1 || endIndex === -1) {
        return null;
      }

      const metadataBlock = unitContent.substring(startIndex, endIndex + endMarker.length);

      // Parse each field
      const schemaVersionMatch = metadataBlock.match(/schema_version:\s*(\S+)/);
      const generatedByMatch = metadataBlock.match(/generated-by:\s*(.+)/);
      const generatedAtMatch = metadataBlock.match(/generated-at:\s*(.+)/);
      const specforgeVersionMatch = metadataBlock.match(/specforge-version:\s*(.+)/);
      const serviceNameMatch = metadataBlock.match(/service-name:\s*(.+)/);
      const binaryPathMatch = metadataBlock.match(/binary-path:\s*(.+)/);

      if (
        !schemaVersionMatch ||
        !generatedByMatch ||
        !generatedAtMatch ||
        !specforgeVersionMatch ||
        !serviceNameMatch ||
        !binaryPathMatch
      ) {
        return null;
      }

      return {
        schema_version: schemaVersionMatch[1] as "1.0",
        generatedBy: generatedByMatch[1].trim(),
        generatedAt: generatedAtMatch[1].trim(),
        specforgeVersion: specforgeVersionMatch[1].trim(),
        serviceName: serviceNameMatch[1].trim(),
        binaryPath: binaryPathMatch[1].trim(),
      };
    } catch {
      return null;
    }
  }

  /**
   * Render dependency lines for systemd [Unit] section
   */
  private renderDependencies(dependsOn: string[]): string[] {
    if (dependsOn.length === 0) {
      return [];
    }

    const lines: string[] = [];
    for (const dep of dependsOn) {
      // Add .service suffix if not present
      const serviceName = dep.endsWith(".service") ? dep : `${dep}.service`;
      lines.push(`Wants=${serviceName}`);
      lines.push(`After=${serviceName}`);
    }
    return lines;
  }

  /**
   * Render environment variables for systemd [Service] section
   */
  private renderEnvironment(env: Record<string, string>): string[] {
    if (Object.keys(env).length === 0) {
      return [];
    }

    const lines: string[] = [];
    for (const [key, value] of Object.entries(env)) {
      lines.push(`Environment=${key}=${value}`);
    }
    return lines;
  }
}