/**
 * Property-based tests for Scope Isolation (Property 14)
 *
 * **Validates: Requirements 7.3**
 *
 * Property 14: Scope Isolation
 * - project_runtime scope: no .specforge.lock created, no opencode.json created/modified, no downgrade detection
 * - user_shared scope: lock is acquired and released, opencode.json is managed
 *
 * Since scope behavior is binary (not random), this test uses deterministic scenarios
 * verified across multiple file configurations generated by fast-check.
 *
 * Key design decisions:
 * - project_runtime uses repair_missing/repair_full modes (as Plugin does), which skip
 *   downgrade detection and opencode.json merge
 * - user_shared uses full/fresh_install modes (as CLI does), which acquire locks,
 *   perform downgrade detection, and merge opencode.json
 */

import { describe, it, expect, afterEach } from "vitest"
import * as fc from "fast-check"
import { join } from "node:path"
import { mkdir, writeFile, readFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { createHash } from "node:crypto"
import { createTempDir, cleanupTempDir } from "../helpers/fixtures"
import { reconcile } from "../../scripts/lib/reconcile"
import type { ReconcileScope, DesiredStateEntry } from "../../scripts/lib/types"
import type { DesiredStateProvider, DiscoveryResult } from "../../scripts/lib/discovery"

// ============================================================
// Helpers
// ============================================================

/** Track temp dirs for cleanup */
const tempDirs: string[] = []

afterEach(async () => {
  for (const dir of tempDirs) {
    await cleanupTempDir(dir)
  }
  tempDirs.length = 0
})

/**
 * Compute SHA-256 hash of content
 */
function sha256(content: string): string {
  return createHash("sha256").update(Buffer.from(content, "utf-8")).digest("hex")
}

/**
 * Create a mock DesiredStateProvider with given scope and entries
 */
function createMockProvider(
  scope: ReconcileScope,
  entries: Map<string, DesiredStateEntry>,
  version = "3.6.0"
): DesiredStateProvider {
  return {
    scope,
    async buildDesiredState(): Promise<DiscoveryResult> {
      return {
        ok: true,
        state: { entries, version },
      }
    },
  }
}

/**
 * Write a source file to the source directory and return its SHA-256 hash
 */
async function writeSourceFile(
  sourceDir: string,
  relativePath: string,
  content: string
): Promise<string> {
  const fullPath = join(sourceDir, ...relativePath.split("/"))
  await mkdir(join(fullPath, ".."), { recursive: true })
  await writeFile(fullPath, content, "utf-8")
  return sha256(content)
}

/**
 * Write a valid Manifest to the target directory
 */
async function writeManifest(
  targetDir: string,
  version: string,
  files: Record<string, { sha256: string; size: number; type: string }>
): Promise<void> {
  const manifest = {
    schema_version: "1.0",
    shared_version: version,
    install_mode: "user_level",
    installed_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    managed_agents: [],
    managed_agent_hashes: {},
    files,
  }
  const manifestPath = join(targetDir, "specforge-manifest.json")
  await writeFile(manifestPath, JSON.stringify(manifest, null, 2), "utf-8")
}

/**
 * Generator for random file content (non-empty)
 */
function arbFileContent(): fc.Arbitrary<string> {
  return fc.string({ minLength: 5, maxLength: 200 })
}

/**
 * Generator for a valid managed relative path with sf- prefix
 */
function arbManagedRelativePath(): fc.Arbitrary<string> {
  const identifier = fc.stringMatching(/^[a-z][a-z0-9_]{2,8}$/)
  return fc.oneof(
    identifier.map((id) => `agents/sf-${id}.md`),
    identifier.map((id) => `tools/sf_${id}.ts`),
    identifier.map((id) => `plugins/sf_${id}.ts`)
  )
}

/**
 * Generator for a set of unique file specs (path + content)
 */
function arbFileSpecs(): fc.Arbitrary<Array<{ path: string; content: string }>> {
  return fc
    .array(fc.tuple(arbManagedRelativePath(), arbFileContent()), {
      minLength: 1,
      maxLength: 5,
    })
    .map((specs) => {
      // Deduplicate by path
      const seen = new Set<string>()
      return specs
        .filter(([path]) => {
          if (seen.has(path)) return false
          seen.add(path)
          return true
        })
        .map(([path, content]) => ({ path, content }))
    })
    .filter((specs) => specs.length > 0)
}

/**
 * Build DesiredStateEntry map from file specs
 */
function buildEntries(
  fileSpecs: Array<{ path: string; content: string; hash: string }>
): Map<string, DesiredStateEntry> {
  const entries = new Map<string, DesiredStateEntry>()
  for (const { path, content, hash } of fileSpecs) {
    entries.set(path, {
      relativePath: path,
      componentType: path.startsWith("agents/")
        ? "agent"
        : path.startsWith("plugins/")
          ? "plugin"
          : "tool",
      sourceHash: hash,
      size: Buffer.byteLength(content, "utf-8"),
    })
  }
  return entries
}


// ============================================================
// Property Tests
// ============================================================

describe("Scope Isolation Properties (Property 14)", () => {
  // Property 14a: project_runtime scope isolation
  //
  // When reconcile is executed with scope "project_runtime" (using repair modes as Plugin does):
  // - No .specforge.lock file is created (no lock acquisition)
  // - No opencode.json is created or modified
  // - No downgrade detection occurs (repair modes skip it)
  //
  // Validates: Requirements 7.3
  it("Property 14a: project_runtime scope — no lock, no opencode.json merge, no downgrade detection", async () => {
    await fc.assert(
      fc.asyncProperty(arbFileSpecs(), async (fileSpecs) => {
        // Setup temp directories
        const sourceDir = await createTempDir("scope-p14a-src-")
        const targetDir = await createTempDir("scope-p14a-tgt-")
        tempDirs.push(sourceDir, targetDir)

        // Write source files and build entries
        const enrichedSpecs: Array<{ path: string; content: string; hash: string }> = []
        for (const { path, content } of fileSpecs) {
          const hash = await writeSourceFile(sourceDir, path, content)
          enrichedSpecs.push({ path, content, hash })
        }
        const entries = buildEntries(enrichedSpecs)

        // Write a manifest with HIGHER version to potentially trigger downgrade
        // (should NOT trigger in project_runtime scope with repair modes)
        await writeManifest(targetDir, "99.0.0", {})

        // Execute reconcile with project_runtime scope using repair_missing mode
        // (this is how Plugin uses reconcile — R7.1, R7.3)
        const result = await reconcile({
          sourceDir,
          targetDir,
          force: false,
          mode: "repair_missing",
          scope: "project_runtime",
          provider: createMockProvider("project_runtime", entries, "3.6.0"),
        })

        // Assertion 1: Reconcile succeeds (no downgrade blocking)
        expect(result.success).toBe(true)

        // Assertion 2: No downgrade detected (repair modes skip downgrade detection)
        expect(result.downgradeDetected).toBe(false)

        // Assertion 3: No lock file created
        expect(existsSync(join(targetDir, ".specforge.lock"))).toBe(false)

        // Assertion 4: No opencode.json created
        expect(existsSync(join(targetDir, "opencode.json"))).toBe(false)
      }),
      { numRuns: 20 }
    )
  })

  // Property 14a2: project_runtime scope with repair_full also isolates
  //
  // Same guarantees as 14a but with repair_full mode (R7.4: invalid RuntimeManifest)
  //
  // Validates: Requirements 7.3
  it("Property 14a2: project_runtime scope with repair_full — same isolation guarantees", async () => {
    await fc.assert(
      fc.asyncProperty(arbFileSpecs(), async (fileSpecs) => {
        // Setup temp directories
        const sourceDir = await createTempDir("scope-p14a2-src-")
        const targetDir = await createTempDir("scope-p14a2-tgt-")
        tempDirs.push(sourceDir, targetDir)

        // Write source files and build entries
        const enrichedSpecs: Array<{ path: string; content: string; hash: string }> = []
        for (const { path, content } of fileSpecs) {
          const hash = await writeSourceFile(sourceDir, path, content)
          enrichedSpecs.push({ path, content, hash })
        }
        const entries = buildEntries(enrichedSpecs)

        // Write a manifest with HIGHER version
        await writeManifest(targetDir, "99.0.0", {})

        // Execute reconcile with project_runtime scope using repair_full mode
        const result = await reconcile({
          sourceDir,
          targetDir,
          force: false,
          mode: "repair_full",
          scope: "project_runtime",
          provider: createMockProvider("project_runtime", entries, "3.6.0"),
        })

        // Assertion 1: Reconcile succeeds (no downgrade blocking)
        expect(result.success).toBe(true)

        // Assertion 2: No downgrade detected
        expect(result.downgradeDetected).toBe(false)

        // Assertion 3: No lock file created
        expect(existsSync(join(targetDir, ".specforge.lock"))).toBe(false)

        // Assertion 4: No opencode.json created
        expect(existsSync(join(targetDir, "opencode.json"))).toBe(false)
      }),
      { numRuns: 20 }
    )
  })

  // Property 14b: user_shared scope — lock is acquired/released, opencode.json is managed
  //
  // When reconcile is executed with scope "user_shared":
  // - Lock is acquired and released (no lock file remains after completion)
  // - opencode.json is created/updated when agents are present (with sourceConfig)
  //
  // Validates: Requirements 7.3
  it("Property 14b: user_shared scope — lock acquired/released, opencode.json managed", async () => {
    await fc.assert(
      fc.asyncProperty(arbFileSpecs(), async (fileSpecs) => {
        // Setup temp directories
        const sourceDir = await createTempDir("scope-p14b-src-")
        const targetDir = await createTempDir("scope-p14b-tgt-")
        tempDirs.push(sourceDir, targetDir)

        // Write source files and build entries
        const enrichedSpecs: Array<{ path: string; content: string; hash: string }> = []
        for (const { path, content } of fileSpecs) {
          const hash = await writeSourceFile(sourceDir, path, content)
          enrichedSpecs.push({ path, content, hash })
        }
        const entries = buildEntries(enrichedSpecs)

        // Build sourceConfig for agents (required for opencode.json merge to register them)
        const sourceConfig: Record<string, { mode: string; model: string; prompt: string; permission: Record<string, string> }> = {}
        for (const { path } of fileSpecs) {
          if (path.startsWith("agents/")) {
            const agentKey = path.replace("agents/", "").replace(".md", "")
            sourceConfig[agentKey] = {
              mode: "subagent",
              model: "anthropic/claude-sonnet-4-20250514",
              prompt: `{file:./agents/${agentKey}.md}`,
              permission: { task: "deny", edit: "ask", bash: "ask" },
            }
          }
        }

        // Execute reconcile with user_shared scope (no existing manifest → fresh)
        const result = await reconcile({
          sourceDir,
          targetDir,
          force: false,
          mode: "full",
          scope: "user_shared",
          provider: createMockProvider("user_shared", entries, "3.6.0"),
          mergeOptions: {
            sourceConfig,
            preserveUserOverrides: true,
            backupBeforeDowngrade: false,
          },
        })

        // Assertion 1: Reconcile succeeds
        expect(result.success).toBe(true)

        // Assertion 2: Lock is released (no lock file remains)
        expect(existsSync(join(targetDir, ".specforge.lock"))).toBe(false)

        // Assertion 3: opencode.json is created when agents are present
        const hasAgents = fileSpecs.some((f) => f.path.startsWith("agents/"))
        if (hasAgents) {
          expect(existsSync(join(targetDir, "opencode.json"))).toBe(true)
          // Verify opencode.json contains sf-* entries for agents under "agent" key
          const opencodeContent = JSON.parse(
            await readFile(join(targetDir, "opencode.json"), "utf-8")
          )
          expect(opencodeContent).toHaveProperty("agent")
          const agentPaths = fileSpecs.filter((f) =>
            f.path.startsWith("agents/")
          )
          for (const { path } of agentPaths) {
            // Agent key is filename without extension
            const agentKey = path.replace("agents/", "").replace(".md", "")
            expect(opencodeContent.agent).toHaveProperty(agentKey)
          }
        }
      }),
      { numRuns: 20 }
    )
  })

  // Property 14c: user_shared scope — downgrade detection is active
  //
  // When reconcile is executed with scope "user_shared" and manifest has higher version:
  // - Downgrade IS detected and blocks execution (without --force)
  //
  // Validates: Requirements 7.3
  it("Property 14c: user_shared scope — downgrade detection blocks without --force", async () => {
    await fc.assert(
      fc.asyncProperty(arbFileSpecs(), async (fileSpecs) => {
        // Setup temp directories
        const sourceDir = await createTempDir("scope-p14c-src-")
        const targetDir = await createTempDir("scope-p14c-tgt-")
        tempDirs.push(sourceDir, targetDir)

        // Write source files and build entries
        const enrichedSpecs: Array<{ path: string; content: string; hash: string }> = []
        for (const { path, content } of fileSpecs) {
          const hash = await writeSourceFile(sourceDir, path, content)
          enrichedSpecs.push({ path, content, hash })
        }
        const entries = buildEntries(enrichedSpecs)

        // Write manifest with HIGHER version → triggers downgrade in user_shared full mode
        await writeManifest(targetDir, "99.0.0", {})

        // Execute reconcile with user_shared scope
        const result = await reconcile({
          sourceDir,
          targetDir,
          force: false,
          mode: "full",
          scope: "user_shared",
          provider: createMockProvider("user_shared", entries, "3.6.0"),
        })

        // Assertion: Downgrade IS detected and blocks execution
        expect(result.success).toBe(false)
        expect(result.downgradeDetected).toBe(true)
        expect(result.error).toContain("Downgrade detected")
      }),
      { numRuns: 20 }
    )
  })

  // Property 14d: user_shared scope does not create project-level runtime structures
  //
  // When reconcile is executed with scope "user_shared":
  // - Only files in the target directory are modified (user-level directory)
  // - No project-level runtime files are touched (no specforge/ directory)
  //
  // Validates: Requirements 7.3
  it("Property 14d: user_shared scope does not create project-level runtime structures", async () => {
    await fc.assert(
      fc.asyncProperty(arbFileSpecs(), async (fileSpecs) => {
        // Setup temp directories
        const sourceDir = await createTempDir("scope-p14d-src-")
        const targetDir = await createTempDir("scope-p14d-tgt-")
        tempDirs.push(sourceDir, targetDir)

        // Write source files and build entries
        const enrichedSpecs: Array<{ path: string; content: string; hash: string }> = []
        for (const { path, content } of fileSpecs) {
          const hash = await writeSourceFile(sourceDir, path, content)
          enrichedSpecs.push({ path, content, hash })
        }
        const entries = buildEntries(enrichedSpecs)

        // Execute reconcile with user_shared scope
        const result = await reconcile({
          sourceDir,
          targetDir,
          force: false,
          mode: "full",
          scope: "user_shared",
          provider: createMockProvider("user_shared", entries, "3.6.0"),
          mergeOptions: {
            sourceConfig: {},
            preserveUserOverrides: true,
            backupBeforeDowngrade: false,
          },
        })

        expect(result.success).toBe(true)

        // Assertion: No project-level runtime directory (specforge/) created in target
        expect(existsSync(join(targetDir, "specforge"))).toBe(false)

        // Assertion: No runtime manifest created (that's project-level)
        expect(existsSync(join(targetDir, "specforge-runtime-manifest.json"))).toBe(false)
      }),
      { numRuns: 20 }
    )
  })
})
