import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import * as fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import * as path from 'node:path';
import { SPEC_DIR_NAME } from '@specforge/types/directory-layout';
import { getCurrentBranch, getHeadCommit, normalizeRelativePath } from './git-governance-core';

const execFileAsync = promisify(execFile);

async function runGit(projectRoot: string, args: string[], allowFailure = false): Promise<{ stdout: string; stderr: string; code: number }> {
  try {
    const { stdout, stderr } = await execFileAsync('git', args, { cwd: projectRoot, maxBuffer: 10 * 1024 * 1024 });
    return { stdout: String(stdout ?? ''), stderr: String(stderr ?? ''), code: 0 };
  } catch (err: any) {
    if (allowFailure) {
      return { stdout: String(err?.stdout ?? ''), stderr: String(err?.stderr ?? err?.message ?? ''), code: Number(err?.code ?? 1) };
    }
    throw new Error(`git ${args.join(' ')} failed: ${String(err?.stderr ?? err?.message ?? 'git command failed')}`);
  }
}

async function writeJson(filePath: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, JSON.stringify(value, null, 2) + '\n', 'utf-8');
}

async function readJsonIfExists<T>(filePath: string, fallback: T): Promise<T> {
  if (!existsSync(filePath)) return fallback;
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf-8')) as T;
  } catch {
    return fallback;
  }
}

function runtimePath(projectRoot: string, ...parts: string[]): string {
  return path.join(projectRoot, SPEC_DIR_NAME, 'runtime', ...parts);
}

function reportsPath(projectRoot: string, ...parts: string[]): string {
  return path.join(projectRoot, SPEC_DIR_NAME, 'reports', ...parts);
}

function safeBranchName(value: string): string {
  return String(value || '')
    .trim()
    .replace(/\\/g, '/')
    .replace(/^\/+|\/+$/g, '')
    .replace(/\s+/g, '-')
    .replace(/[^A-Za-z0-9._\/-]/g, '-')
    .replace(/\/+/g, '/');
}

function inferProvider(url: string | undefined, hint?: string): string {
  if (hint) return hint;
  const text = String(url ?? '').toLowerCase();
  if (text.includes('github.com')) return 'github';
  if (text.includes('gitlab.com')) return 'gitlab';
  if (text.includes('gitee.com')) return 'gitee';
  if (text.includes('bitbucket.org')) return 'bitbucket';
  if (text.includes('http') || text.includes('@')) return 'generic_git';
  return 'unknown';
}

function parseRemotes(stdout: string): Record<string, { fetch_url?: string; push_url?: string }> {
  const remotes: Record<string, { fetch_url?: string; push_url?: string }> = {};
  for (const line of stdout.split(/\r?\n/).filter(Boolean)) {
    const match = line.match(/^(\S+)\s+(\S+)\s+\((fetch|push)\)$/);
    if (!match) continue;
    const [, name, url, kind] = match;
    remotes[name] ||= {};
    if (kind === 'fetch') remotes[name].fetch_url = url;
    if (kind === 'push') remotes[name].push_url = url;
  }
  return remotes;
}

export async function gitPrPlan(input: {
  projectRoot: string;
  sourceBranch?: string;
  targetBranch?: string;
  remoteName?: string;
  provider?: string;
  title?: string;
  body?: string;
  writePlan?: boolean;
}) {
  const currentBranch = input.sourceBranch ?? (await getCurrentBranch(input.projectRoot)) ?? '';
  const sourceBranch = safeBranchName(currentBranch);
  if (!sourceBranch) throw new Error('SOURCE_BRANCH_REQUIRED');
  const targetBranch = safeBranchName(input.targetBranch || 'main');
  const remoteName = input.remoteName || 'origin';
  const headCommit = await getHeadCommit(input.projectRoot);
  const remotes = parseRemotes((await runGit(input.projectRoot, ['remote', '-v'], true)).stdout);
  const remote = remotes[remoteName] ?? {};
  const provider = inferProvider(remote.fetch_url || remote.push_url, input.provider);
  const plan = {
    schema_version: 'git_pr_plan.v1',
    success: true,
    provider_type: provider,
    remote_name: remoteName,
    source_branch: sourceBranch,
    target_branch: targetBranch,
    head_commit: headCommit,
    title: input.title || `Merge ${sourceBranch} into ${targetBranch}`,
    body: input.body || 'Generated by SpecForge Git Governance stage 4.',
    mode: 'plan_only',
    requires_user_review: true,
    remote,
    updated_at: new Date().toISOString(),
  };
  if (input.writePlan !== false) {
    const planPath = runtimePath(input.projectRoot, 'git_pr_plan.json');
    await writeJson(planPath, plan);
    return { ...plan, plan_path: normalizeRelativePath(path.relative(input.projectRoot, planPath)) };
  }
  return plan;
}

export async function gitWorktreePlan(input: {
  projectRoot: string;
  branchName: string;
  baseRef?: string;
  worktreePath?: string;
  createBranch?: boolean;
  writePlan?: boolean;
}) {
  const branchName = safeBranchName(input.branchName);
  if (!branchName) throw new Error('BRANCH_NAME_REQUIRED');
  const baseRef = input.baseRef || 'main';
  const defaultPath = path.resolve(input.projectRoot, '..', `${path.basename(input.projectRoot)}--${branchName.replace(/[\/]/g, '-')}`);
  const worktreePathAbs = path.resolve(input.worktreePath || defaultPath);
  const headCommit = await getHeadCommit(input.projectRoot).catch(() => '');
  const plan = {
    schema_version: 'git_worktree_plan.v1',
    success: true,
    branch_name: branchName,
    base_ref: baseRef,
    worktree_path: worktreePathAbs,
    create_branch: input.createBranch !== false,
    head_commit: headCommit,
    mode: 'plan_only',
    updated_at: new Date().toISOString(),
  };
  if (input.writePlan !== false) {
    const planPath = runtimePath(input.projectRoot, 'git_worktree_plan.json');
    await writeJson(planPath, plan);
    return { ...plan, plan_path: normalizeRelativePath(path.relative(input.projectRoot, planPath)) };
  }
  return plan;
}

export async function gitWorktreeCreate(input: {
  projectRoot: string;
  branchName: string;
  baseRef?: string;
  worktreePath?: string;
  createBranch?: boolean;
  confirmed?: boolean;
}) {
  if (input.confirmed !== true) throw new Error('WORKTREE_CREATE_REQUIRES_USER_CONFIRMATION');
  const plan = await gitWorktreePlan({ ...input, writePlan: false });
  const args = plan.create_branch
    ? ['worktree', 'add', '-b', plan.branch_name, plan.worktree_path, plan.base_ref]
    : ['worktree', 'add', plan.worktree_path, plan.branch_name];
  const result = await runGit(input.projectRoot, args, true);
  const registryPath = runtimePath(input.projectRoot, 'git_worktrees.json');
  const existing = await readJsonIfExists<any>(registryPath, { schema_version: 'git_worktrees.v1', worktrees: [] });
  const nextWorktrees = [
    ...(existing.worktrees ?? []).filter((item: any) => item.branch_name !== plan.branch_name && item.worktree_path !== plan.worktree_path),
    { branch_name: plan.branch_name, base_ref: plan.base_ref, worktree_path: plan.worktree_path, created_at: new Date().toISOString(), result_code: result.code },
  ];
  await writeJson(registryPath, { schema_version: 'git_worktrees.v1', updated_at: new Date().toISOString(), worktrees: nextWorktrees });
  return {
    ...plan,
    success: result.code === 0,
    mode: 'executed',
    code: result.code,
    stdout: result.stdout,
    stderr: result.stderr,
    registry_path: normalizeRelativePath(path.relative(input.projectRoot, registryPath)),
  };
}

export async function gitStackedBranchPlan(input: {
  projectRoot: string;
  parentBranch: string;
  childBranch: string;
  workItemId?: string;
  childWorkItemId?: string;
  writePlan?: boolean;
}) {
  const parentBranch = safeBranchName(input.parentBranch);
  const childBranch = safeBranchName(input.childBranch);
  if (!parentBranch || !childBranch) throw new Error('PARENT_AND_CHILD_BRANCH_REQUIRED');
  const headCommit = await getHeadCommit(input.projectRoot).catch(() => '');
  const plan = {
    schema_version: 'git_stacked_branch_plan.v1',
    success: true,
    parent_branch: parentBranch,
    child_branch: childBranch,
    work_item_id: input.workItemId ?? null,
    child_work_item_id: input.childWorkItemId ?? null,
    current_head: headCommit,
    mode: 'plan_only',
    merge_order: [childBranch, parentBranch],
    warning: 'Merge stacked branches from child to parent, then parent to target branch after gates pass.',
    updated_at: new Date().toISOString(),
  };
  if (input.writePlan !== false) {
    const planPath = runtimePath(input.projectRoot, 'git_stacked_branch_plan.json');
    await writeJson(planPath, plan);
    return { ...plan, plan_path: normalizeRelativePath(path.relative(input.projectRoot, planPath)) };
  }
  return plan;
}

export async function gitReleaseTagPlan(input: {
  projectRoot: string;
  tagName: string;
  targetRef?: string;
  message?: string;
  remoteName?: string;
  writePlan?: boolean;
}) {
  const tagName = String(input.tagName || '').trim();
  if (!tagName) throw new Error('TAG_NAME_REQUIRED');
  const targetRef = input.targetRef || 'HEAD';
  const remoteName = input.remoteName || 'origin';
  const resolvedTarget = (await runGit(input.projectRoot, ['rev-parse', targetRef], true)).stdout.trim();
  const existing = await runGit(input.projectRoot, ['tag', '--list', tagName], true);
  const plan = {
    schema_version: 'git_release_tag_plan.v1',
    success: true,
    tag_name: tagName,
    target_ref: targetRef,
    target_commit: resolvedTarget,
    remote_name: remoteName,
    message: input.message || `release: ${tagName}`,
    tag_exists: existing.stdout.trim() === tagName,
    mode: 'plan_only',
    requires_user_confirmation: true,
    updated_at: new Date().toISOString(),
  };
  if (input.writePlan !== false) {
    const planPath = reportsPath(input.projectRoot, `git_release_tag_plan_${tagName.replace(/[^A-Za-z0-9._-]/g, '-')}.json`);
    await writeJson(planPath, plan);
    return { ...plan, plan_path: normalizeRelativePath(path.relative(input.projectRoot, planPath)) };
  }
  return plan;
}

export async function gitReleaseTagCreate(input: {
  projectRoot: string;
  tagName: string;
  targetRef?: string;
  message?: string;
  confirmed?: boolean;
}) {
  if (input.confirmed !== true) throw new Error('RELEASE_TAG_CREATE_REQUIRES_USER_CONFIRMATION');
  const plan = await gitReleaseTagPlan({ ...input, writePlan: false });
  if (plan.tag_exists) throw new Error('TAG_ALREADY_EXISTS');
  const result = await runGit(input.projectRoot, ['tag', '-a', plan.tag_name, plan.target_ref, '-m', plan.message], true);
  return { ...plan, mode: 'executed', success: result.code === 0, code: result.code, stdout: result.stdout, stderr: result.stderr };
}

type AgentLock = {
  lock_name: string;
  owner: string;
  work_item_id?: string | null;
  paths: string[];
  acquired_at: string;
  expires_at: string;
};

function isExpired(lock: AgentLock, now = Date.now()): boolean {
  return new Date(lock.expires_at).getTime() <= now;
}

export async function gitAgentLockAcquire(input: {
  projectRoot: string;
  lockName: string;
  owner: string;
  workItemId?: string;
  paths?: string[];
  ttlMinutes?: number;
  confirmed?: boolean;
}) {
  if (input.confirmed !== true) throw new Error('AGENT_LOCK_ACQUIRE_REQUIRES_USER_CONFIRMATION');
  const lockName = String(input.lockName || '').trim();
  const owner = String(input.owner || '').trim();
  if (!lockName || !owner) throw new Error('LOCK_NAME_AND_OWNER_REQUIRED');
  const ttlMs = Math.max(1, Number(input.ttlMinutes || 120)) * 60 * 1000;
  const now = Date.now();
  const locksPath = runtimePath(input.projectRoot, 'git_agent_locks.json');
  const existing = await readJsonIfExists<any>(locksPath, { schema_version: 'git_agent_locks.v1', locks: [] });
  const active = (existing.locks ?? []).filter((lock: AgentLock) => !isExpired(lock, now));
  const conflict = active.find((lock: AgentLock) => lock.lock_name === lockName && lock.owner !== owner);
  if (conflict) return { success: false, error: 'AGENT_LOCK_CONFLICT', conflict, locks_path: normalizeRelativePath(path.relative(input.projectRoot, locksPath)) };
  const nextLock: AgentLock = {
    lock_name: lockName,
    owner,
    work_item_id: input.workItemId ?? null,
    paths: (input.paths ?? []).map(normalizeRelativePath),
    acquired_at: new Date(now).toISOString(),
    expires_at: new Date(now + ttlMs).toISOString(),
  };
  const locks = [...active.filter((lock: AgentLock) => lock.lock_name !== lockName || lock.owner !== owner), nextLock];
  await writeJson(locksPath, { schema_version: 'git_agent_locks.v1', updated_at: new Date().toISOString(), locks });
  return { success: true, lock: nextLock, locks_path: normalizeRelativePath(path.relative(input.projectRoot, locksPath)) };
}

export async function gitAgentLockRelease(input: {
  projectRoot: string;
  lockName: string;
  owner?: string;
  force?: boolean;
  confirmed?: boolean;
}) {
  if (input.confirmed !== true) throw new Error('AGENT_LOCK_RELEASE_REQUIRES_USER_CONFIRMATION');
  const lockName = String(input.lockName || '').trim();
  if (!lockName) throw new Error('LOCK_NAME_REQUIRED');
  const locksPath = runtimePath(input.projectRoot, 'git_agent_locks.json');
  const existing = await readJsonIfExists<any>(locksPath, { schema_version: 'git_agent_locks.v1', locks: [] });
  const before = existing.locks ?? [];
  const after = before.filter((lock: AgentLock) => {
    if (lock.lock_name !== lockName) return true;
    if (input.force === true) return false;
    return input.owner ? lock.owner !== input.owner : true;
  });
  await writeJson(locksPath, { schema_version: 'git_agent_locks.v1', updated_at: new Date().toISOString(), locks: after });
  return { success: true, released_count: before.length - after.length, locks_path: normalizeRelativePath(path.relative(input.projectRoot, locksPath)) };
}
