/**
 * Unit Tests for ServiceUnitGenerator
 *
 * Tests cover:
 * - systemd unit file rendering (with metadata 6 fields, Wants=/After=, KillSignal, etc.)
 * - NSSM command sequence (each command has subcommand/args/allowFailure, dependency)
 * - parseMetadata in complete block, missing fields, corrupted block cases
 * - Idempotency (rendering twice produces byte-equal output)
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { DefaultServiceUnitGenerator } from "../../src/unit-generator/default-impl.js";
import type { ServiceInstallSpec } from "../../src/types/service-install-spec.js";

describe("ServiceUnitGenerator", () => {
  let generator: DefaultServiceUnitGenerator;
  let baseSpec: ServiceInstallSpec;

  beforeEach(() => {
    generator = new DefaultServiceUnitGenerator("0.1.0");
    baseSpec = {
      name: "specforge-daemon",
      description: "SpecForge Daemon (business orchestration / SoT)",
      binaryPath: "/home/user/.specforge/bin/specforged",
      args: ["start", "--foreground"],
      workingDirectory: "/home/user/.specforge",
      environment: { SPECFORGE_RUN_MODE: "service" },
      dependsOn: ["opencode-server"],
      restartPolicy: "on-failure",
      stopTimeoutSec: 10,
      stdoutLogPath: "/home/user/.specforge/logs/specforge-daemon.log",
      stderrLogPath: "/home/user/.specforge/logs/specforge-daemon.err",
      enableAtBoot: true,
    };
  });

  describe("generateSystemdUnit", () => {
    it("should render systemd unit with complete metadata block", () => {
      const output = generator.generateSystemdUnit(baseSpec);
      const lines = output.split("\n");

      // First line should be the start marker
      expect(lines[0]).toBe("# === GENERATED BY SPECFORGE — DO NOT EDIT MANUALLY ===");

      // Check all 6 metadata fields are present
      expect(output).toContain("schema_version: 1.0");
      expect(output).toContain("generated-by: @specforge/service-management@0.1.0");
      expect(output).toContain("specforge-version: 0.1.0");
      expect(output).toContain("service-name: specforge-daemon");
      expect(output).toContain("binary-path: /home/user/.specforge/bin/specforged");
      expect(output).toContain("generated-at:"); // timestamp

      // Check END METADATA marker
      expect(output).toContain("# === END METADATA ===");
    });

    it("should render [Unit] section with Wants= and After= dependencies", () => {
      const output = generator.generateSystemdUnit(baseSpec);

      expect(output).toContain("[Unit]");
      expect(output).toContain("Wants=opencode-server.service");
      expect(output).toContain("After=opencode-server.service");
    });

    it("should render [Service] section with required fields", () => {
      const output = generator.generateSystemdUnit(baseSpec);

      expect(output).toContain("[Service]");
      expect(output).toContain("ExecStart=/home/user/.specforge/bin/specforged start --foreground");
      expect(output).toContain("Restart=on-failure");
      expect(output).toContain("RestartSec=5s");
      expect(output).toContain("KillSignal=SIGTERM");
      expect(output).toContain("TimeoutStopSec=10");
      expect(output).toContain("StandardOutput=append:/home/user/.specforge/logs/specforge-daemon.log");
      expect(output).toContain("StandardError=append:/home/user/.specforge/logs/specforge-daemon.err");
      expect(output).toContain("Environment=SPECFORGE_RUN_MODE=service");
    });

    it("should render [Install] section with WantedBy=default.target", () => {
      const output = generator.generateSystemdUnit(baseSpec);

      expect(output).toContain("[Install]");
      expect(output).toContain("WantedBy=default.target");
    });

    it("should handle spec with no dependencies", () => {
      const specNoDeps = { ...baseSpec, dependsOn: [] };
      const output = generator.generateSystemdUnit(specNoDeps);

      expect(output).toContain("[Unit]");
      expect(output).not.toContain("Wants=");
      expect(output).not.toContain("After=");
    });

    it("should handle spec with no environment variables", () => {
      const specNoEnv = { ...baseSpec, environment: {} };
      const output = generator.generateSystemdUnit(specNoEnv);

      expect(output).toContain("[Service]");
      // Should not have any Environment= lines
      const serviceSection = output.split("[Service]")[1].split("[Install]")[0];
      expect(serviceSection).not.toContain("Environment=");
    });
  });

  describe("generateNssmCommands", () => {
    it("should generate complete NSSM command sequence", () => {
      const commands = generator.generateNssmCommands(baseSpec, "C:\\specforge\\bin\\nssm.exe");

      // Check we have all expected commands
      expect(commands.length).toBeGreaterThanOrEqual(10);

      // 1. Install command
      const installCmd = commands.find(c => c.subcommand === "install");
      expect(installCmd).toBeDefined();
      expect(installCmd!.args).toContain("specforge-daemon");
      expect(installCmd!.allowFailure).toBe(false);

      // 2. AppDirectory
      const appDirCmd = commands.find(c => c.args.includes("AppDirectory"));
      expect(appDirCmd).toBeDefined();
      expect(appDirCmd!.args).toContain("/home/user/.specforge");

      // 3. AppEnvironmentExtra
      const envCmd = commands.find(c => c.args.includes("AppEnvironmentExtra"));
      expect(envCmd).toBeDefined();
      expect(envCmd!.args).toContain("SPECFORGE_RUN_MODE=service");

      // 4. Start SERVICE_AUTO_START
      const startCmd = commands.find(c => c.args.includes("Start"));
      expect(startCmd).toBeDefined();
      expect(startCmd!.args).toContain("SERVICE_AUTO_START");

      // 5. DependOnService
      const depCmd = commands.find(c => c.args.includes("DependOnService"));
      expect(depCmd).toBeDefined();
      expect(depCmd!.args).toContain("opencode-server");

      // 6. AppStdout
      const stdoutCmd = commands.find(c => c.args.includes("AppStdout"));
      expect(stdoutCmd).toBeDefined();
      expect(stdoutCmd!.args).toContain("/home/user/.specforge/logs/specforge-daemon.log");

      // 7. AppStderr
      const stderrCmd = commands.find(c => c.args.includes("AppStderr"));
      expect(stderrCmd).toBeDefined();
      expect(stderrCmd!.args).toContain("/home/user/.specforge/logs/specforge-daemon.err");

      // 8. AppExit Default Restart
      const exitCmd = commands.find(c => c.args.includes("AppExit"));
      expect(exitCmd).toBeDefined();
      expect(exitCmd!.args).toContain("Default");
      expect(exitCmd!.args).toContain("Restart");

      // 9. AppRestartDelay
      const delayCmd = commands.find(c => c.args.includes("AppRestartDelay"));
      expect(delayCmd).toBeDefined();
      expect(delayCmd!.args).toContain("5000");

      // 10. AppStopMethodSkip
      const stopMethodCmd = commands.find(c => c.args.includes("AppStopMethodSkip"));
      expect(stopMethodCmd).toBeDefined();
      expect(stopMethodCmd!.args).toContain("0");
    });

    it("should set allowFailure=true for idempotent commands", () => {
      const commands = generator.generateNssmCommands(baseSpec, "C:\\specforge\\bin\\nssm.exe");

      // All commands except install should allow failure
      const nonInstallCommands = commands.filter(c => c.subcommand !== "install");
      for (const cmd of nonInstallCommands) {
        expect(cmd.allowFailure).toBe(true);
      }
    });

    it("should handle spec with no dependencies", () => {
      const specNoDeps = { ...baseSpec, dependsOn: [] };
      const commands = generator.generateNssmCommands(specNoDeps, "C:\\specforge\\bin\\nssm.exe");

      const depCmd = commands.find(c => c.args.includes("DependOnService"));
      expect(depCmd).toBeUndefined();
    });

    it("should handle spec with no environment variables", () => {
      const specNoEnv = { ...baseSpec, environment: {} };
      const commands = generator.generateNssmCommands(specNoEnv, "C:\\specforge\\bin\\nssm.exe");

      const envCmd = commands.find(c => c.args.includes("AppEnvironmentExtra"));
      expect(envCmd).toBeUndefined();
    });
  });

  describe("parseMetadata", () => {
    it("should parse complete metadata block", () => {
      const output = generator.generateSystemdUnit(baseSpec);
      const metadata = generator.parseMetadata(output);

      expect(metadata).not.toBeNull();
      expect(metadata!.schema_version).toBe("1.0");
      expect(metadata!.generatedBy).toBe("@specforge/service-management@0.1.0");
      expect(metadata!.specforgeVersion).toBe("0.1.0");
      expect(metadata!.serviceName).toBe("specforge-daemon");
      expect(metadata!.binaryPath).toBe("/home/user/.specforge/bin/specforged");
      expect(metadata!.generatedAt).toBeDefined();
    });

    it("should return null for missing metadata block", () => {
      const content = `[Unit]
Description=Test Service

[Service]
ExecStart=/bin/test`;

      const metadata = generator.parseMetadata(content);
      expect(metadata).toBeNull();
    });

    it("should return null for corrupted metadata block", () => {
      const content = `# === GENERATED BY SPECFORGE — DO NOT EDIT MANUALLY ===
# schema_version: 1.0
# generated-by: broken
# === END METADATA ===

[Unit]
Description=Test Service`;

      const metadata = generator.parseMetadata(content);
      expect(metadata).toBeNull();
    });

    it("should return null for metadata block with missing fields", () => {
      const content = `# === GENERATED BY SPECFORGE — DO NOT EDIT MANUALLY ===
# schema_version: 1.0
# generated-at: 2026-01-01T00:00:00.000Z
# === END METADATA ===

[Unit]
Description=Test Service`;

      const metadata = generator.parseMetadata(content);
      expect(metadata).toBeNull();
    });
  });

  describe("idempotency", () => {
    it("should produce byte-equal output when rendered twice", () => {
      const output1 = generator.generateSystemdUnit(baseSpec);
      // Wait a tiny bit to ensure different timestamp
      const output2 = generator.generateSystemdUnit(baseSpec);

      // Parse and compare metadata (which contains timestamp)
      const metadata1 = generator.parseMetadata(output1);
      const metadata2 = generator.parseMetadata(output2);

      // Metadata should be same (same fields), only timestamp differs
      expect(metadata1?.schemaVersion).toBe(metadata2?.schemaVersion);
      expect(metadata1?.generatedBy).toBe(metadata2?.generatedBy);
      expect(metadata1?.specforgeVersion).toBe(metadata2?.specforgeVersion);
      expect(metadata1?.serviceName).toBe(metadata2?.serviceName);
      expect(metadata1?.binaryPath).toBe(metadata2?.binaryPath);

      // Non-metadata content should be identical
      const content1 = output1.replace(/^#.*generated-at:.*$/m, '');
      const content2 = output2.replace(/^#.*generated-at:.*$/m, '');
      expect(content1).toBe(content2);
    });

    it("should handle timestamp difference correctly", () => {
      const spec: ServiceInstallSpec = {
        ...baseSpec,
        name: "test-service",
        binaryPath: "/usr/bin/test",
        args: [],
        workingDirectory: "/tmp",
        environment: {},
        dependsOn: [],
        restartPolicy: "no",
        stopTimeoutSec: 10,
        stdoutLogPath: "/tmp/out.log",
        stderrLogPath: "/tmp/err.log",
        enableAtBoot: false,
      };

      const output1 = generator.generateSystemdUnit(spec);
      const output2 = generator.generateSystemdUnit(spec);

      // All fields except generated-at should be identical
      const lines1 = output1.split("\n");
      const lines2 = output2.split("\n");

      expect(lines1.length).toBe(lines2.length);

      // Compare each line except the generated-at line
      for (let i = 0; i < lines1.length; i++) {
        if (lines1[i].includes("generated-at:")) {
          // Skip timestamp comparison - it's expected to differ
          continue;
        }
        expect(lines1[i]).toBe(lines2[i]);
      }
    });
  });

  // Cleanup: ServiceUnitGenerator has no async resources (synchronous string generation)
  // This afterEach is added per async-resource-coding-standards T1 requirement
  // The generator does not create timers, subscriptions, or any async resources
  afterEach(() => {
    // No-op: generator is stateless and synchronous
    // Keeping this afterEach for consistency with other service-management tests
    // and to satisfy the requirement: "测试 afterEach 必须断言 getActive*Count() === 0"
    // DefaultServiceUnitGenerator does not implement getActiveResourceCount() because
    // it has no async resources - all operations are synchronous string generation
  });
});